### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by delliott90** [pypa/pypi-support#1005]
### PyPI Username

delliott90

### Reason for request

I lost my 2FA access because the Google authenticator app got deleted from my phone. I don't remember ever setting up any backup codes.

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
