### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sagudeloo** [pypa/pypi-support#1048]
### PyPI Username

sagudeloo

### Reason for request

Hello a lost my two factor authentication app for pypi.org and I can't log in.
Thank for help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
