### ISSUE TITLE
Transfer ownership of vapi-runtime, vapi-common-client, vapi-client-bindings

### ISSUE THREAD

**Issue by jobingeo** [pypa/pypi-support#105]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/vapi-runtime/
`PROJECT_NAME`: https://pypi.org/project/vapi-common-client/
`PROJECT_NAME`:  https://pypi.org/project/vapi-client-bindings/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/jobingeorge/

**Reasons for the request**
We believe these packages are uploaded by a user who is not maintaining it and it is currently in ABANDONED state.
There is a request from community to move the packages to PyPi, https://github.com/vmware/vsphere-automation-sdk-python/issues/38 

**Maintenance or replacement?**
A new version will be uploaded.
https://github.com/vmware/vsphere-automation-sdk-python/tree/master/lib/vapi-client-bindings
https://github.com/vmware/vsphere-automation-sdk-python/tree/master/lib/vapi-common-client
https://github.com/vmware/vsphere-automation-sdk-python/tree/master/lib/vapi-runtime

**Contact and additional research**
We couldn't email the maintainer as his email details are not available.
https://pypi.org/user/Claire.Deng/

**Comment by jamadden** [comment]
Based on https://github.com/vmware/vsphere-automation-sdk-python/commits?author=jobingeo it does appear that user @jobingeo is associated with https://github.com/vmware

I've emailed the address PyPI has on file for the owner account. I was unable to locate any other potential means of contact with any degree of certainty. Since the request is under PEP 541's abandoned clause, the owner has up to six weeks to respond (and PyPI moderators should attempt contact a few times before then). If that time period elapses please feel free to ping this issue as a reminder.

The files currently on PyPI appear to contain copyrighted code:
```
       │ File: vapi_common_client-2.5.0/com/vmware/vapi/metadata_client.py
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # -*- coding: utf-8 -*-
   2   │ #---------------------------------------------------------------------------
   3   │ # Copyright 2016 VMware, Inc.  All rights reserved.
   4   │
   5   │ # AUTO GENERATED FILE -- DO NOT MODIFY!
   6   │ #
   7   │ # vAPI stub file for package com.vmware.vapi.metadata.
   8   │ #---------------------------------------------------------------------------
```

IANAL, but it's possible that the [Intellectual Property Policy](https://www.python.org/dev/peps/pep-0541/#intellectual-property-policy) might apply in some fashion.

**Comment by tianhao64** [comment]
@jamadden Thanks for looking into this and appreciate your help. The user who uploaded the package was not from VMware and was not the author of this package. We(VMware eng team) would like to reclaim the ownership of these packages and the pypi repos. 
Since the package was wrongly uploaded by a non-author, does that violate the copyright? Could you please advise what are the steps to follow if it violates the Intellectual Property Policy? Will we reclaim the repo faster than PEP 541? Thanks a lot for your help!

**Comment by jamadden** [comment]
All I know is that the PEP 541 section I linked to outlines the policy on IP violations, but since I'm not a lawyer I don't want to try to interpret it. Specifically, I don't know if any copyright violation has been committed; that would be up to lawyers.

**Comment by mariolenz** [comment]
> `PROJECT_NAME`: https://pypi.org/project/vapi-runtime/
> `PROJECT_NAME`: https://pypi.org/project/vapi-common-client/
> `PROJECT_NAME`: https://pypi.org/project/vapi-client-bindings/

I get a "404 Page Not Found" for these at the moment. Did Claire.Deng already deleted these projects in order for you to take ownership / create them again?

**Comment by jamadden** [comment]
Uh, yes, it seems that those projects have been deleted. There was a password reset for the owner today after I emailed that account, and a login for the first time. AFAICS those projects are now gone.

**Comment by tianhao64** [comment]
Ah. Great news! Thanks a lot for the quick help!

**Comment by jobingeo** [comment]
Thanks.
As the user deleted the project, is there any further cooling/waiting period (under PEP 541 abandoned clause)? Can we re-use these packages?

**Comment by jamadden** [comment]
I think they're up for grabs.

**Comment by EclipzzeX** [comment]
@tianhao64 Are these going to reposted to pypi, or the github updated?  Currently the "pip install git+https://github.com/vmware/vsphere-automation-sdk-python.git" results in "HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/vapi-runtime/"
Thanks

**Comment by jobingeo** [comment]
@EclipzzeX  This could be related to https://github.com/vmware/vsphere-automation-sdk-python/issues/195 . Please see your pip version, upgrade if required.  If still facing issue, please open up a issue in https://github.com/vmware/vsphere-automation-sdk-python/issues

@jamadden Thanks for your help. Closing the issue.
