### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rskcse1** [pypa/pypi-support#1067]
### PyPI Username

rsk.cse1

### Reason for request

Lost 2FA authentication app and security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by rskcse1** [comment]
Kindly help me recover my account

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
