### ISSUE TITLE
PEP 541: Transfer ownership of project "packages"

### ISSUE THREAD

**Issue by chrahunt** [pypa/pypi-support#109]
Attempting to publish to project "packages" fails. I am requesting transfer of ownership in case this is because the project is taken but with no releases.

**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/packages

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/chrahunt

**Reasons for the request**

Publish a new project.

**Maintenance or replacement?**

Replacement. The repo for the new project is https://github.com/chrahunt/packages

**Contact and additional research**

Not applicable - no project seems to be available under the current name.

**Comment by jamadden** [comment]
The `packages` project on PyPI was registered on 2019-09-13 by uploading a file that was deleted within hours (the account that did the upload was created immediately before uploading and hasn't been used since). That qualifies under the PEP definition of an invalid project. I'll ask the admins to initiate the transfer.

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by chrahunt** [comment]
Thank you both for your help!
