### ISSUE TITLE
PEP 541 Request: winrm

### ISSUE THREAD

**Issue by nitzmahone** [pypa/pypi-support#1114]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/winrm/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nitzmahone

### Reasons for the request

The current package looks like a typosquatting setup from someone that's been doing a lot of it. We'd probably just yank the release and put a "did you mean pywinrm?" note on it.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/diyan/pywinrm

### Contact and additional research

N/A beyond issue report on pywinrm from a community member that's noticed a bad pattern...

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @nitzmahone, it does look like a "good natured" typosquatting but unfortunately the package since it does have functionality, albeit copied from `pywinrm`, we're forced to start a reachability process before it can be transferred.

Hopefully the owner will reply soon and we can proceed with the transfer, alternatively and admin could place `winrm` in the prohibited project names list which would save you the trouble of uploading a project yourself.

**Comment by yeraydiazdiaz** [comment]
The owner replied and allowed the project to be placed in the prohibited project names list /cc @pypa/warehouse-admins

**Comment by ewdurbin** [comment]
This is complete.
