### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jdciaravino1** [pypa/pypi-support#1117]
### PyPI Username

jdciaravino

### Reason for request

I have lost access to my account with the username jdciaravino, because I no longer have the details for the 2FA. If I cannot recover the account then, I would prefer to just delete it. I do not have the recovery codes

Regards,

Joe

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
