### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by M-Davies** [pypa/pypi-support#1119]
### PyPI Username

`M-Davies`

### Reason for request

Lost access to 2FA authentication app and recovery codes. If access cannot be restored, please just delete the account so I can make a new one.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
