### ISSUE TITLE
PEP 541 Request: cuda

### ISSUE THREAD

**Issue by jakirkham** [pypa/pypi-support#1143]
### Project to be claimed

`cuda`: https://pypi.org/project/cuda

### Your PyPI username

`jakirkham`: https://pypi.org/user/jakirkham

### Reasons for the request

The user that created the package has been identified as a potential name squatter ( https://github.com/pypa/pypi-support/issues/188 ).

Also for a project we are working at at NVIDIA, we would like to claim this name.

### Maintenance or replacement?

Replacement

### Contact and additional research

Could not find any contact information for the user. Also the package itself appears to be a `setup.py` doesn't appear to install anything

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jakirkham** [comment]
@di would you be able to take a look? Or do you know who we should ask? 🙂

**Comment by jakirkham** [comment]
@ewdurbin would you be able to advise on next steps here? 🙂

Sorry for reaching out blindly here. We are hoping to do a release soon and are trying to figure out how to get unblocked 😅 Any thoughts would be welcome

**Comment by di** [comment]
I've determined that the `cuda` project is an invalid project per PEP 541 (https://www.python.org/dev/peps/pep-0541/#invalid-projects) because the project is name squatting.

I've transferred ownership of the project to `jakirkham`. Please note that you will be unable to make a release with `cuda-0.0.1.tar.gz` as this filename has already been used.

**Comment by jakirkham** [comment]
Thanks Dustin! 😀
