### ISSUE TITLE
PEP 541 Request: django-waitress

### ISSUE THREAD

**Issue by VanL** [pypa/pypi-support#1145]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/django-waitress

### Your PyPI username

`USER_NAME`: https://pypi.org/user/VanL

### Reasons for the request

The current project has had no releases other than the one initial release, three years ago, and is no longer installable without forcing it due to it specifying that it only works with Waitress <2.0.

I can't find a public repo anywhere, nor a public url, nor an email address.

### Maintenance or replacement?

Maintenance

### Contact and additional research

Searched on github and Google for django-waitress repos; did not find any.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by excitedleigh** [comment]
Hello!

This is my package; it was published before my gender transition and hasn't been updated since so isn't associated with my new PyPI login (PyPI doesn't allow username changes, grumble grumble).

This was brought to my attention by someone at the company that I worked for when I created it (where I no longer work). They apparently still depend on it. I've replied to him to clarify what he'd like to do with it, and will update here when he replies.

**Comment by excitedleigh** [comment]
Okay, after clarification he's happy for it to be given to Van so @VanL I've invited you to be an owner of the package.

I regret I also don't remember where the source code repository is. If you desperately need commit history I'm happy to trawl through my backups, otherwise starting from the sdist should work fine :)

**Comment by yeraydiazdiaz** [comment]
Thanks for resolving this @excitedleigh.
