### ISSUE TITLE
Question: How to rename spotify-videos to vidify

### ISSUE THREAD

**Issue by marioortizmanero** [pypa/pypi-support#120]
Hello. I'm the creator and maintainer of [spotify-videos](https://pypi.org/project/spotify-videos/). This package is going to change its name in the next release and I wanted to know how this can be done on PyPi. GitHub for example lets you rename it and will redirect any users going to the old URL to the new one. Something similar (and probably better suited for this case) happens with the [AUR](https://aur.archlinux.org/): you can rename the package, and when the users update the package, it changes its name automatically in the system.

I've done some research about this online and I [didn't find much information](https://stackoverflow.com/questions/17460747/change-case-of-package-name-on-pypi). Even if this is not possible on PyPi, I wanted to know the official response from the devs for other people in the future to find this.

**Project to be claimed**
`spotify-videos`: https://pypi.org/project/spotify-videos/

**Your PyPI username**
`marioortizmanero`: https://pypi.org/user/marioortizmanero/

**Reasons for the request**
See the top message.

**Maintenance or replacement?**
Maintenance, the project will be renamed and I will continue to work on it.

**Comment by jamadden** [comment]
[Removing the PEP541 label and title because this doesn't seem to be about claiming an existing but abandoned distribution name.]

If you want to change a distribution's name, then usually one would upload the new distribution, followed by uploading one last version of the old distribution which does nothing but contain a dependency on the *new* distribution (with no version constraints). In this way, users that have dependencies on the old distribution name (mostly) automatically simply start installing the new distribution. Users that have version constraints on the old distribution name will continue to be able to use those older distributions unchanged.

For example, [ZODB](https://pypi.org/project/ZODB/) used to to be called [ZODB3](https://pypi.org/project/ZODB3/). When the name changed with version 4.0, one last release of [ZODB3](https://pypi.org/project/ZODB3/) was made, and its only contents were dependencies in setup.py on `ZODB`.

```python
# ZODB3.tar.gz setup.py
setup(
    name='ZODB3',
   version=the_highest_zodb3_version_ever(),
   install_requires=['ZODB']
)
```

**Comment by marioortizmanero** [comment]
That's a very good solution, thanks!

You can close the issue if you want.
