### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Zafarsun** [pypa/pypi-support#1228]
### PyPI Username

Zafar2410

### Reason for request

I didn't add any authentication app to my PyPI account previously and that's why i could not access my PyPI account right now, however I 've access to my email and I've my username and password.

Please help to log in my PyPI account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
