### ISSUE TITLE
Limit Request: tesseract-ocr-data - 150 MB

### ISSUE THREAD

**Issue by MOBSkuchen** [pypa/pypi-support#1241]
### Project URL

https://pypi.org/project/tesseract-ocr-data/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

150

### Which indexes

PyPI

### Reasons for the request

I want to make a project that includes the tesseract-ocr so devs can use it without,
having to install all of the files, and can just import this package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I'm confused by this request. You're asking for 90MB but for the total project size? The current default file upload limit is 100MB and the default project size limit is 10GB, you shouldn't need a limit increase.

**Comment by pradyunsg** [comment]
I'm going to go ahead and deny this request, since this project:

> - project contains large pre-trained machine learning models
> - project includes a large JAR file

Looking at https://github.com/MOBSkuchen/tesseract-ocr-data, this project seems to be a bunch of large `.dll`, `.jar` and `.exe` files bundled up into the distribution. This means that the project is windows-specific but would generate a platform-independent wheel.

Notably, https://github.com/MOBSkuchen/tesseract-ocr-data/tree/main/tesseract-pack/tessdata looks like a repackaging of https://github.com/tesseract-ocr/tessdata after a Windows-specific build.
