### ISSUE TITLE
Limit Request: py-tgcalls - 100 GB

### ISSUE THREAD

**Issue by Laky-64** [pypa/pypi-support#1323]
### Project URL

https://pypi.org/project/py-tgcalls

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

102400

### Which indexes

PyPI

### Reasons for the request

I want to upload at same time the pre-compiled node modules of my python library, is possible to increase the limit size?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi! This is a fairly large limit request! This would enable this project to be the 12th largest project on PyPI (per https://pypi.org/stats/).

Right now, this project is under an year old and has 40 releases. Each release has 25 wheels at ~20 MB each (~500 MB).

- Have you explored any mechanisms to make the distribution sizes smaller?
- Have you considered reducing the frequency of the project's releases?
- Could you clarify why you want to ship a `node_modules` directory instead of a package-lock.json file for the project?

**Comment by Laky-64** [comment]
Because some server can have installation problems, so I directly decided to compile them myself, in order to reduce Build times, however I am trying to keep myself with the available storage space, You could also compromise, as I know, at least 50Gb, just for when I do the betas, and Major versions, (The betas I always delete them after the beta period)

**Comment by di** [comment]
To be clear, when you say "pre-compiled node modules", are you talking about Node.js?

**Comment by Laky-64** [comment]
Yes, because my lib My library interfaces with nodejs, I would like to avoid having to compile the end user as it takes a long time, moreover as it is now it is really simple and ready to use

**Comment by di** [comment]
Hi! Right now the default total project size limit for all projects is 10GB, and this project is sitting at 3.6GB, which is well below this limit. Please feel free to come back once your project is closer to the 10GB limit and we can revisit the request here.
