### ISSUE TITLE
PEP 541 Request: eegtools

### ISSUE THREAD

**Issue by acpuchades** [pypa/pypi-support#1330]
### Project to be claimed

`EEGTools`: https://pypi.org/project/EEGtools

### Your PyPI username

`acpuchades`: https://pypi.org/user/acpuchades

### Reasons for the request

Project has not received a new commit for more than 5 years, according to its README it never ever got out from alpha phase and GitHub project is currently archived.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/acpuchades/eegtools

### Contact and additional research

Didn't find any email address in the project webpage, couldn't find any other means to contact the owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @acpuchades, I will start the reachability process for your request, hopefully the owner will reply soon and we can proceed with the transfer.

**Comment by breuderink** [comment]
I am still internalising what this process entails. I have archived to original EEGtools repository, since I don't have the time nor resources to update it to Python 3. So I would welcome a maintainer for the project. 

However, this seems not to be a request to maintain the project, but to claim the PyPI name for a different project. I don't think that is a good idea. People are still using the package for publications (e.g. [1]), and as a dependency in software (e.g. [2]).

[1] https://www.nature.com/articles/s41598-020-65112-y
[2] https://github.com/fnielsen/brede

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @breuderink, you are correct, the request is for replacement.

PEP 541 states that transfer will not be carried out against the will of the owner so I will close this request.
