### ISSUE TITLE
Limit Request: graphscope - 256 MB

### ISSUE THREAD

**Issue by lidongze0629** [pypa/pypi-support#1444]
### Project URL

graphscope

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

256MB

### Which indexes

PyPI

### Reasons for the request

Hello, In our coming release, we will support the standalone mode of [GraphScope](https://github.com/alibaba/GraphScope), which packages the necessary runtime dependencies, so could you help us to increase the size limit?  Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sighingnow** [comment]
Hi @di,

Could you please help us to increase the size limit for our package `graphscope`?

GraphScope is a graph computation engine, previously we only included client side code in our wheel package and the package was about 25MB and the size limit didn't affect us.

We begin to bundle the engine part to the wheel package as well since this release to deliver to the end-user (in Python community) better user-experience to try graphscope in their local environment after typing `pip3 install graphscope`. We have managed to strip the binary to reduce the package to about 200MB, but it is still beyond the default size limit of pypi.

Thanks in advance!

**Comment by sighingnow** [comment]
Our package contains prebuilt binaries, as well as precompiled jars.

**Comment by sighingnow** [comment]
Hi @ewdurbin would you be able to take a look at this request? We have cut a new release but currently are stuck on this issue.

Thanks in advance!

**Comment by lidongze0629** [comment]
@pradyunsg would you please take a look at this please? 🙏

**Comment by pradyunsg** [comment]
Bumped the limit to 300 MB.

**Comment by sighingnow** [comment]
> 

Thanks!
