### ISSUE TITLE
PEP 541 Request: pypam

### ISSUE THREAD

**Issue by cparcerisas** [pypa/pypi-support#1476]
### Project to be claimed

pypam

### Your PyPI username

https://pypi.org/user/cparcerisas/

### Reasons for the request

I would like to take over the name pypam at pypi. I am developing the pypam package (https://pypi.org/project/lifewatch-pypam/, source: https://github.com/lifewatch/pypam), but I had to use lifewatch-pypam so it could be released. The name pypam is not available, but I can't find the project (and even less the owner of the project) to ask him/her to release the name so I can use it. There has been no release in pypi, and there is also no public github repository that seems to be active with this name. So there is no homepage of the project and therefore the owner can't be reached.
I believe pypam can not be considered a malware name. 
In the Support Issues there is no results if I search using the word pypam. 

Thank you! 

### Source code repositories URLs

https://github.com/lifewatch/pypam
(this is my code, I can't find anyone else's code)

### Contact and additional research

There is no pypi home page. There is no public github page with a release. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by roelderickx** [comment]
@encukou Subject of #355, please have a look.

**Comment by encukou** [comment]
PyPAM is also the name of Python bindings for PAM, the Unix [Pluggable authentication module](https://en.wikipedia.org/wiki/Pluggable_authentication_module). Although the PyPAM project is not active anymore, it's still available in some distros. See package pages for:
* [Gentoo](https://packages.gentoo.org/packages/dev-python/pypam/changelog)
* [Fedora](https://src.fedoraproject.org/rpms/PyPAM)

This PyPAM predates both PyPI and GitHub. Since it needs PAM headers installed, it wouldn't be very useful to distribute it via PyPI . Nevertheless, a `pypam` dependency *will* be satisfied by the distro package on systems that have it installed.

Since the original PyPAM is not active, I think the name can be unblocked. But keep in mind that this might confuse some users/deployments.
The last release of PyPAM was 0.5.0 (2010?). Could you bump the version of the new pypam to 1.0+, to help avoid confusion?

cc @xsuchy (last Fedora maintainer), @mgorny (Gentoo maintainer), @hroncok

**Comment by yeraydiazdiaz** [comment]
Hello @cparcerisas, `pypam` was [placed in the prohibited project names list](https://github.com/pypa/pypi-support/issues/355#issuecomment-621834283) some time ago, and given the situation that @encukou described I'm not sure the best course of action is to release the project name.

I'll close the request for now but if any @pypa/warehouse-admins feel it's safe to release the project please do so.
