### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by flipmcf** [pypa/pypi-support#1520]
### PyPI Username

flipmcf

### Reason for request

I am assuming that my old iPhone (which died) contained my 2FA auth config on Google Authenticator.   I set it up and never used it.  I also did not save a recovery code.

I don't have anything I manage on PyPi - so a recovery should be a very safe process.

I'm sorry for the inconvenience.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
