### ISSUE TITLE
PEP 541 Request: pvi

### ISSUE THREAD

**Issue by thomascobb** [pypa/pypi-support#1558]
### Project to be claimed

`pvi`: https://pypi.org/project/pvi

### Your PyPI username

`dls_controls`: https://pypi.org/user/dls_controls

### Reasons for the request

The name does not appear to be in use, my organisation (pypi username: dls_controls) has a project with this name that we wish to publish. Uploading to pypi gives the error `The name 'pvi' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.`

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/epics-containers/pvi

### Contact and additional research

This is a new project that cannot currently be uploaded as its name is too similar to an existing project. However I cannot work out which project it is too similar to...

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by thomascobb** [comment]
I believe this is the same situation as another one of our projects, `tickit` encountered in #1327: it is in the list of prohibited names. The previous issue was solved by @yeraydiazdiaz and @ewdurbin

**Comment by yeraydiazdiaz** [comment]
Hi @thomascobb, `pvi` is not in the prohibited project names list, the error refers to this portion of https://pypi.org/help/#project-name:

> The project name is too similar to an existing project and may be confusable

From what I can gather from the warehouse code this is a check run in the database before a project is created so it's hard to say which project it's finding as too similar, my intuition is that since the name is quite short it's easier to find similar existing projects.

Maybe @pypa/warehouse-admins can provide more details?

**Comment by ewdurbin** [comment]
The name collides with https://pypi.org/project/pvl/ in the "ultra normalized" scheme from https://github.com/pypa/warehouse/pull/10498.

The name has been released to `dls_controls` User on pypi.org

**Comment by thomascobb** [comment]
Thank you, much appreciated!
