### ISSUE TITLE
PEP 541 Request: Ansible

### ISSUE THREAD

**Issue by webknjaz** [pypa/pypi-support#160]
**Project to be claimed**

`Ansible`: https://pypi.org/project/ansible-py3/

**Your PyPI username**

`webknjaz`: https://pypi.org/user/webknjaz

**Reasons for the request**

I believe that this project may be used for the name squatting. Even though I haven't confirmed any malicious code added there, the publisher probably shouldn't upload misleading description (it's basically the same as official Ansible dist has) and use almost the same name. It also doesn't have any pointers to what version of code exactly it publishes.

**Maintenance or replacement?**

Nope, just want to prevent bad faith use...

**Contact and additional research**

There's no uploader info in the dist. It contains the same email as the official Ansible dist.

**Comment by jamadden** [comment]
That project appears to be owned by Github user @mrk-its who [recently contributed a PR to upstream ansible](https://github.com/ansible/ansible/pull/54958). Perhaps @mrk-its can respond here?

**Comment by mrk-its** [comment]
@webknjaz @jamadden I've uploaded this package because I was not able to get my PR merged to ansible for 8 months (this package is simply my fork of ansible with changes from that PR) You are right, I definitely should use different name and modify description (will do). I'll remove this package completely after new release of upstream ansible (with my changes).

**Comment by webknjaz** [comment]
@mrk-its please do the change and thanks for understanding!
