### ISSUE TITLE
Mass name squat by user: tcw

### ISSUE THREAD

**Issue by blsqr** [pypa/pypi-support#1610]
### PyPI user performing the mass project name squatting

https://pypi.org/user/tcw/

### Additional information

This user has 120 projects registered on PyPI. To me, this looks like name squatting for the following reasons:

* many packages are just 2-letter package names
* releases are on the same days (6th Jan 2021 or 29th Dec 2020)
* there were no further releases since those initial ones
* The package homepage links are often broken
* There seems to be some random text used for package descriptions and there is indeed some code in the packages – it is unclear to me, where this code comes from, though, and if it may be distributed by the author (or whether it is just scraped from somewhere)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by thorwhalen** [comment]
First of all, I apologize: I noticed this thread only recently, when I noticed that some things weren’t working anymore because some of my names were taken away and looked into what happened. I now see I received email notifications of the thread, but they were buried in the plethora of github emails I get. I hope I didn’t inconvenience anyone too much.

I didn’t answer right away because I immediately looked up similar issues, and seeing how subjective, and sometimes trolling, the whole thing could be, I was hesitant to step into that time consuming and possibly emotional pit. This is why there’s things like pep 541 — to try to give a basis to the madness, though those who want to fight still do so with interpretation . 

That said, let me shyly give this a chance. 

Hopefully a bit of declaration of intent can help shed on some light on the behavior and be sufficient to appease and resolve.

The effort stems from two major needs/wants. In a nutshell:
Making a big repository of utils I’ve accumulated more clean and reusable
Giving myself the tools to deal with the problem above more systematically

Over the years, when I spot something in a project that is not private or particular to the project, I try to extract the reusable functionality and put it up on public github. It makes it easier to reuse in other projects, collaborate with their teams, etc. The way I was doing this wasn’t sustainable — one humongous repository with hundreds of, sometimes totally unrelated functionalities in them, no packaging, no dependency management, etc. 

I’ve been wanting to tackle this ugly problem for a while, and a year a half ago I had a bit of time to look into it. I wanted to break things up in such a way that future projects didn’t have to clone and install a mammoth, but rather just pip install only what was needed. I also am hoping that having things more broken up and themed will enable me (and whoever I’m working with at the time) to have a specific home for utils that will be developed in the future; thus allowing even the little modules I have to snowball into something more significant.

Know that quite a bit of manual work went into it, in case automation is the issue here. If it’s the “shouldn’t be too fast” part of automation that is the critique, know that I spent extra time, in fact, to automate some of the manual work I had already done. This is because I felt that this “project outgrows itself” problem is common enough (to me) that I’d like to achieve my concrete goal leaving some tooling crumbs on the way. 

Again, this is not me targeting a bunch of names and slapping code into it. This is me taking a big corpus of code that existed already, and was already broken up in packages, sub packages, and modules, and make these into fine-grained pip installable packages.

**Comment by thorwhalen** [comment]
Let me, now, address some of the constructive critiques I see above.


### many packages are just 2-letter package names

Yeah… that’s one I hesitated on for some time. Pypi suggests that packages names should be “short and memorable”. I prefer both, and genuinely tried to get better names, but I was going down a rabbit hole there (an interesting one involving semantic analysis etc., but won’t go into detail here). I favor short over descriptive and just couldn’t get (available) descriptive names short enough. 

The saving grace for me was to realize three things:
A lot of the top packages have names that are only loosely connected with the subject matter. Ask someone who doesn’t know the package what pandas or six or black does.
When the package is used, the name isn’t a problem (again… pandas, six, black)
Branding 101: more your name is non-specific, more flexibility you have to follow the inevitable shift in the content, avoid the need of rebranding (in our case re-naming). 

I saw that there were a lot of two-letter available packages, so that sealed the deal:
the abundant availability of two letter package names meant that they weren’t convoited names, so I shouldn’t be blocking too many folk from any “perfect name for their thing”
they’re as short as they can be

Please also note that I did spend some time mapping the names to the packages. 
I didn’t have to, but I still did. Now it’s FAR from perfect (I regret some choices now, but it’s a bit hard to change without being disruptive), but many DO have a link only known to me. Here are a few examples, from the pretty good, to pretty far fetched:
* `rv` - Utils to work with randomness - R.V stands for [Random Variable](https://en.wikipedia.org/wiki/Random_variable), a fundamental concept in statistics
* `cr` - binary classification count results - C.R. = Count Results
* `un` - Analyzing classes - “un” is the indefinite article in French (so as in… AN instance of…)
* `kw` - Utils to work with storage - K for key and W for write, because in storage we often write something somewhere, referenced by a key

I just came up with another TODO: I should probably add these “name rationale” explanations in the READMEs. 


### releases are on the same days (6th Jan 2021 or 29th Dec 2020)

Yes. I explained my intent and process in the previous comment. 


### there were no further releases since those initial ones

Actually, I got back to it recently, and there has been quite a few changes. 


### The package homepage links are often broken

Thanks for the heads up. I didn’t realize that.
I made a script to spot which were broken. 
It should be completely repaired now.


### There seems to be some random text used for package descriptions and there is indeed some code in the packages – it is unclear to me, where this code comes from, though, and if it may be distributed by the author (or whether it is just scraped from somewhere)

I think you’ll find that the text for package descriptions is not at all random, but describes, as shortly as I could, what the contents are about. 

The code wasn’t scraped. It’s mine. Well, except for a few modules that are edits of some other open source code I found and wanted to shape to my liking. I always reference these in the module’s doc in this case.

**Comment by thorwhalen** [comment]
So, hopefully I’ve demonstrated that this is neither a shameful squatting of names nor a rogue experiment, and we won’t have to go into the weeds of opinions.

It is FAR from perfect, and I’m still trying to figure out how to achieve what I want to achieve, but I tried to leave it in a fairly clean state when I first published these, and have recently made some more improvements.

**Comment by blsqr** [comment]
Thank you very much for providing more background on this, @thorwhalen! With this knowledge, I agree with you that this is not name squatting – I hope you understand why it looked much different to me when I opened this issue.

So… closing this. Thanks again!
