### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by digitalbottle** [pypa/pypi-support#1637]
### PyPI Username

Bottle

### Reason for request

Statement: This pypi acount was applied using  exactly the same email address as my github account.
Issue: I lost my mobile device and buy a new one, the account in okta app cannot be recovered, and unfortunately, I didn't generate recovery code back then. That's  why I'm here looking for help.
Looking forward to your reply, thank you.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
