### ISSUE TITLE
PEP 541 Request: medusa

### ISSUE THREAD

**Issue by lshamis** [pypa/pypi-support#1659]
### Project to be claimed

`medusa`: https://pypi.org/project/medusa

### Your PyPI username

`lshamis`: https://pypi.org/user/lshamis

### Reasons for the request

I believe the existing medusa project has been abandoned. The last update was in 2003.

### Maintenance or replacement?

Replacement

### Contact and additional research

I have reached out to the maintainer [A.M. Kuchling](mailto:amk@amk.ca) on three occasions: Nov 18 2021, Nov 22 2021, and Jan 25 2022. I have not heard back.
The maintainer's webpage is up and running (http://amk.ca/), but the medusa specific page is no longer valid http://amk.ca/python/code/medusa.html

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by lshamis** [comment]
@akuchling

**Comment by yeraydiazdiaz** [comment]
Hello @lshamis, `medusa` seems to have a [fair amount of daily downloads](https://pypistats.org/packages/medusa) despite of the long time since the last release. I'm not sure replacing the project would be the right decision in this case so I'm going to close the request. Hopefully you can find another name that would be suitable for your project.
