### ISSUE TITLE
PEP 541 Request: css-sprite

### ISSUE THREAD

**Issue by ionelmc** [pypa/pypi-support#1708]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/css-sprite

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ionel

### Reasons for the request

I don't get why I can't publish that package. I can't seem to find any css-sprite package already published.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ionelmc/python-css-sprite

### Contact and additional research

No idea what's going on. Is the name normalization buggy?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @ionelmc, I believe the problem is that the name is too similar to https://pypi.org/project/csssprite/. There was a change in PyPI recently disallowing project whose name is too close to other projects to prevent dependency confusion attacks, a @pypa/warehouse-admins can confirm if that's the case.

The `csssprite` project does look abandoned, we could start a PEP 541 process and transfer that name to you. If you really want `css-sprite` it may be possible for an admin to remove `csssprite` allowing you to publish `css-sprite`, although I'm not sure if the system allows for that.

**Comment by yeraydiazdiaz** [comment]
Hi @ionelmc, this is not PEP 541 issue, as I mentioned before it's a case of the name being too similar to another project and Warehouse rejecting it. The only thing we can do at this point is wait for an admin to assess whether it's possible to bypass it for you.

**Comment by ewdurbin** [comment]
css-sprite project name released to [ionel](https://pypi.org/user/ionel)

conflict was with https://pypi.org/project/csssprite/ which seems to be unmaintained.
