### ISSUE TITLE
File Limit Request: bigbench - 400 MB

### ISSUE THREAD

**Issue by ethansdyer** [pypa/pypi-support#1782]
### Project URL

GitHub: https://github.com/google/BIG-bench
PyPI: https://pypi.org/project/bigbench

### Does this project already exist?

- [x] Yes

### New limit

0.4GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The Beyond the Imitation Game Benchmark ([BIG-bench](https://github.com/google/BIG-bench)) is a collaborative machine learning benchmark intended to probe large language models and extrapolate their future capabilities. It contains over 200 tasks. The project has been active since January 2021. We do not expect the project to grow significantly in size moving forward.

[**Note**, the project does not exist as part of PyPI yet, but I could not submit the request without checking the box]

### How large is each release?

~336 MB

The project consists of an api for submitting and evaluating tasks (problems for language models to solve), as well as the tasks themselves (specified as python or json files). The bulk of the release is the task data.

### How frequently do you make a release?

We are somewhat flexible on this. The preference is to have a github action that repackages on every push (currently a few a week, will stabilize in the near future), but if this is prohibitive we can reduce the cadence.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ethansdyer** [comment]
Hi. It seems like the `Does this project already exist?` check box needs to be checked here. This request is for a new PyPI project. Would you like me to create a skeleton project first?

Thank you!

**Comment by pradyunsg** [comment]
Yes. From the description of that checkbox:

> This project MUST EXIST for an increased limit to be set.
>
> An empty 0.0.0 release may be uploaded, if the project doesn't exist. You can delete this release immediately after uploading it.

**Comment by ethansdyer** [comment]
Thank you! This is now done. Package is here: https://pypi.org/project/bigbench

**Comment by ethansdyer** [comment]
Hi. I am just pinging this again to see if there is anything else needed? Thank you!

**Comment by pradyunsg** [comment]
FWIW, you had used the wrong template for filing this issue. You were hitting the per-file limit of 100 MB, instead of the project-wide limit of 10 GB. I'll take that as a note that the templates need to better guide users to the right thing. :)

> The preference is to have a github action that repackages on every push (currently a few a week, will stabilize in the near future), but if this is prohibitive we can reduce the cadence.

There is a total project size limit of 10 GB, so automated releases like that are likely to fill up that quota quickly. In general, it is slightly preferable to do fewer releases -- especially when the project is large (like this is) since there is a decent amount of traffic on PyPI driven by mirroring tools, which download these files regardless of whether they're being used.

---

I've gone ahead and increased the per-file upload limit to 400 MB, on PyPI. This project does not exist on TestPyPI and, thus, the limit has not been increased there. If you need an increase there, please create the project and file a new issue.

Please be mindful of the frequency of your releases with this size limit.
