### ISSUE TITLE
PEP 541 Request: iris

### ISSUE THREAD

**Issue by jwon** [pypa/pypi-support#180]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/iris/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/jwon

**Reasons for the request**

This package has been abandoned. The last release was 3 years ago. 

**Maintenance or replacement?**

I intended to replace the "iris" project with: https://github.com/linkedin/iris

My project has been around for over 3 years -- the team just hasn't gotten around to uploading to PyPI. Now that our development workflow has changed, it would benefit us greatly to be able to publish the package onto PyPI for us and others to use!

**Contact and additional research**

I tried emailing the listed author email on 2020-01-30, but that bounced immediately. Also the project Homepage link doesn't even resolve DNS anymore.

**Comment by jamadden** [comment]
I've emailed the address listed for the project page and confirm that it immediately was returned ("The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser"). (The domain illumon.com is still registered, even though www.illumon.com isn't in DNS; a request for illumon.com redirects to https://deephaven.io) I also tried emailing the verified address PyPI has on file for the owner of the project (which did not bounce).

The same PyPI account owns a different project which has a GitHub project. I've opened https://github.com/bcdev/jpy/issues/172 to attempt to contact the owner that way.

I've verified that @jwon has committed to the listed repository for the new project. (May I suggest, assuming the name transfer is accomplished, being sure to add multiple owners—not just maintainers—to the project, and/or using a shared owner account. Transfer requests because "the owner left the company" are regrettably common.)

For my own curiosity, will `iris` replace https://pypi.org/project/irisapi/, which lists the same homepage?

**Comment by devinrsmith** [comment]
Hi @jwon & @jamadden,

I work at Deephaven. I'll reach out to our team to figure out what our plan is going forward. Sorry for the bounced emails - we'll make sure we update all the relevant contact information so this doesn't happen again.

Thanks,
-Devin

**Comment by jwon** [comment]
> For my own curiosity, will `iris` replace https://pypi.org/project/irisapi/, which lists the same homepage?

@jamadden , you are correct. Assuming Deephaven does not need this package anymore, it will replace https://pypi.org/project/irisapi/

**Comment by devinrsmith** [comment]
My company originally published our packages under the iris PyPi repository. We received a request to help disambiguate the project amongst the other "iris" projects, and so we moved our real package to the illumon-iris repository, and served up a RuntimeError for the iris repository directing users as appropriate. Even though the project hasn't been updated in a long time, it still comes in handy when somebody installs the wrong package:

```
>>> import iris
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/iris/__init__.py", line 18, in <module>
    """)
RuntimeError:

Ambiguous 'iris' package.
Please use either:
  illumon-iris - Python integration for Illumon Iris, a time-series database
     - pip install illumon-iris
     - https://pypi.python.org/pypi/illumon-iris
     - https://www.illumon.com/

  SciTools Iris - Python library for analysing and visualising meteorological and oceanographic data sets
    - http://scitools.org.uk/iris/

  info.gianlucacosta.iris - A general-purpose library for Python
    - pip install info.gianlucacosta.iris
    - https://pypi.python.org/pypi/info.gianlucacosta.iris
```

As such, I don't think it makes sense to transfer the repository name. I'm happy to add a quick description and link to the irisapi repository. @jwon, if you'd like to follow up, please contact us at python@deephaven.io.

Thanks.

**Comment by jwon** [comment]
Thank you for the explanation! I appreciate the context.

I would like to propose that this might meet the definition of an "Invalid Project" in [PEP 541](https://www.python.org/dev/peps/pep-0541/#invalid-projects).  According to the PEP, it says that one of the reasons a package is considered invalid is when a:
> project is name squatting (package has no functionality or is empty);

I feel like using the package to redirect users rather than providing packaged code is not the intended use case for PyPI and is basically name squatting.

I hope you do not take my comment with hostility! I only have the best of intentions and would like to explore all avenues before considering this closed!

@devinrsmith @jamadden Thoughts?

**Comment by devinrsmith** [comment]
No offense taken. I'd argue that the package doesn't match the definition of an "Invalid Project", as it's not empty, and provides some functionality (IMO). The crux being how you define "functionality". Assuming we'll need official PyPi input.

**Comment by jamadden** [comment]
In the past, when a project has needed to change names, we've explicitly encouraged the maintainers to leave behind a forwarding project under the old name. Sometimes they print an error, but it's preferred if they actually have a dependency on the new project so that installing by the old name actually winds up installing the new project too (that works best, of course, if the imports can be made compatible). An example that springs immediately to mind is ZODB3 (the old name). It still exists under that name, but just to list a bunch of dependencies (ZODB, BTrees, etc).

So I personally wouldn't consider the existing iris package to be invalid.

**Comment by jamadden** [comment]
That said, according to https://pypistats.org/packages/iris, daily downloads are pretty low (<5) for `iris`, so perhaps not many people are benefitting from it. (zodb3 still gets a few hundred, but that may be older versions too; pypistats doesn't break it down by version.)

**Comment by jwon** [comment]
Okay, this all makes sense to me.

I won't pursue claiming ownership of the iris package anymore as it looks like it meets the criteria for a valid project!

@devinrsmith it would be great if you could help me get irisapi listed as part of the iris repository. 

Thank you all.

**Comment by jamadden** [comment]
Thanks everyone. I'm going to close this issue now.
