### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MrHemlock** [pypa/pypi-support#1847]
### PyPI Username

`browndj3`

### Reason for request

I lost my authentication device.  I'm unsure whether it was my old phone or some other previous device.  I am also unable to locate my recovery codes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I'm seeing a successful login on June 25, 2021. As such, closing this. Please open a new request if you are still unable to access your account.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
