### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BenjaminRueth** [pypa/pypi-support#189]
Request for account recovery.

## PyPI Username

`precice`

---

##  Reason for request

Reason:

I tried to reset the password for my account using the [password reset](https://pypi.org/account/request-password-reset/) functionality. I have got access to the recovery email address and I'm able to receive the *Password reset request* email. However, if I try to reset the password using the token, it does not work and I see the message *Error Invalid token: request a new password reset link*. Can you help me?

**Comment by ewdurbin** [comment]
Hi @BenjaminRueth, I don't see any outstanding issues that would interfere with the password reset flow. Is it possible something is corrupting or otherwise mishandling the link that is sent in the password reset request email?

You might want to attempt another password reset and compare the HTML and plain text versions, the password reset link should look like:

`https://pypi.org/account/reset-password/?token=<token>`

Where `<token>` is a long string including some special characters such as `.`, `-`, and `_`.

**Comment by BenjaminRueth** [comment]
I finally found out that the way how emails were forwarded to me caused trouble. The token from the mail in my inbox was broken. Accessing the mail directly on the server that takes care of the forwarding worked for me. I still do not really understand what's going wrong, but this is now definitely a problem on my side.

Thanks for your help @ewdurbin!

**Comment by henrymcbean** [comment]
Used google autofill to generate the password when registering and I cannot see it in the password manager. Had to use hlmcbean@gmail.com as it was not excepting "henry_mcbean@hotmail.com" account. I received the register confrimation email but it required me to enter the password and the reset password confimation email is also asking for the password so I cannot reset it.
