### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by fselmo** [pypa/pypi-support#1943]
### PyPI Username

`fselmo`

### Reason for request

Lost 2FA within a broken phone and it is not in the older phone I activated. I can currently release using username and password via command line but that option will not be available soon.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by fselmo** [comment]
@ewdurbin curious if this is still the way to go about this 🤔

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
