### ISSUE TITLE
Project Limit Request: tf-gpu - 30GB

### ISSUE THREAD

**Issue by ssbuild** [pypa/pypi-support#1961]
### Project URL

https://pypi.org/project/tf-gpu/

### Does this project already exist?

- [X] Yes

### New limit

30 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We're releasing for main tensorflow gpu package and we're hitting the project size limit ,hope you can increased project size to 30G, I will do rarely upload.
We build tensorflow using the environment as follow 
cuda 11.6 
cudnn 8.4 
nccl 2.12
tensorrt: 8.4  optional
nvidia Compute Capability 6.0 6.1 7.0 7.5 8.0 8.6
and with intel mkl support , and build  only for linux , and only for tensorflow==1.15 and tensorflow >=2.8

### How large is each release?

Total ~1.7GB/release

Each Linux wheel has ~571MB

For each python version, we need ~571MB  We support 3 Python versions (python3.8 python3.9,python3.10) in parallel, so this leads to ~1.7GB per release.

### How frequently do you make a release?

quarter

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @ssbuild :wave:
I see that within two days you seem to have reach the project size limit, however you mentioned that you will rarely upload. Is that the case? otherwise, I do this you reaching the 30GB limit in maybe 12 more releases.

On the other hand, I see that you have 3 packages for Python 3.8, 3.9 and 3.10 as you mentioned. Have you explored the usage of the [Limited API](https://docs.python.org/3/c-api/stable.html#c.Py_LIMITED_API)? if you adapt your CPython code, you would be able to release only 1 wheel that's compatible for versions from 3.6 onward.
I know it's not a straight forward step, but I'm curious if you have consider this, to avoid having 3 large wheels.

Complementary to that, do you have in those 3 wheels components that are identical and can be used independently of the Python version? you could create `tf-gpu-something` that someone has those 'common files' and declare it as a dependency of the `td-gpu` package.

Have a nice week!

**Comment by ssbuild** [comment]
> Hey @ssbuild 👋 I see that within two days you seem to have reach the project size limit, however you mentioned that you will rarely upload. Is that the case? otherwise, I do this you reaching the 30GB limit in maybe 12 more releases.
> 
> On the other hand, I see that you have 3 packages for Python 3.8, 3.9 and 3.10 as you mentioned. Have you explored the usage of the [Limited API](https://docs.python.org/3/c-api/stable.html#c.Py_LIMITED_API)? if you adapt your CPython code, you would be able to release only 1 wheel that's compatible for versions from 3.6 onward. I know it's not a straight forward step, but I'm curious if you have consider this, to avoid having 3 large wheels.
> 
> Complementary to that, do you have in those 3 wheels components that are identical and can be used independently of the Python version? you could create `tf-gpu-something` that someone has those 'common files' and declare it as a dependency of the `td-gpu` package.
> 
> Have a nice week!

I'm glad to receive your reply.
firstly , I just uploaded some newer version of existing that builded , such as tf-1.15 is  widely used to training and infer service.
secondly, because support more nvidia version, so the volume is slightly big.
thirdly Limited API is not a good choice for me, because to modify pybind11, is not an easy thing for me, and can affect performance.
finally, 30 g space is enough for me, then I can only maintain the major version , from now on, i will do rarely upload.  looking forward to your reply.
@cmaureir

**Comment by cmaureir** [comment]
Thanks for your follow up @ssbuild.
I've set the project limit for `tf-gpu` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend!
