### ISSUE TITLE
PEP 541 Request: botbase

### ISSUE THREAD

**Issue by ooliver1** [pypa/pypi-support#1978]
### Project to be claimed

`botbase`: https://pypi.org/project/botbase

### Your PyPI username

`ooliver1`: https://pypi.org/user/ooliver1

### Reasons for the request

There seems to be no owner but I am unable to upload to that name, receiving a `400 BAD REQUEST` error from `pypa/gh-action-pypi-publish`

### Maintenance or replacement?

Replacement

### Source code repositories URLs

current - unknown, no code is uploaded
new - https://github.com/ooliver1/botbase

### Contact and additional research

I am unable to contact the owner as there is no project uploaded on `botbase` so I have not attempted to make contact

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @ooliver1, you haven't specified the error but I'm guessing the problem is that the name is very similar to https://pypi.org/project/Bot-Base/

Given the similarity of the names I would suggest picking a different name for your project so your users would not inadvertendly install a different project.

I will close your request as a transfer is not possible.
