### ISSUE TITLE
File Limit Request: SYSTEMDS - 200 MB

### ISSUE THREAD

**Issue by j143** [pypa/pypi-support#2032]
### Project URL

https://pypi.org/project/systemds/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

SystemDS is an open source ML system for the end-to-end data science lifecycle. It has been active since 2015 (as open source).

- With our new major release, backend upgrades added new libraries which are higher in size.
- We add libraries of Hadoop (jar files), and others
- No example data is bundled.

### Reasons for the request

Yes. Generally with major releases, backend upgrades add new libraries which might be higher in size. We try our best to optimize, though.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @j143 thanks for the detailed explanation.
I've set the upload limit for `systemds` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
I do encourage you to look for different ways to include such dependencies, because it might be the case that your wheel size increases, maybe you can have additional packages as dependencies with certain libraries, like hadoop on a separate wheel that is installed as a dependency of the `systemds` package.
Have a nice weekend!
