### ISSUE TITLE
Project Limit Request: pulumi-azure-native - 30 GB

### ISSUE THREAD

**Issue by danielrbradley** [pypa/pypi-support#2067]
### Project URL

https://pypi.org/manage/project/pulumi-azure-native

### Does this project already exist?

- [X] Yes

### New limit

30G

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project provides an SDK for managing all resources with Azure's cloud service and is therefore around 50 MB per-release. Releases are quite frequent (often daily) as we track all changes from Microsoft. We've hit the 10 GB limit a number of times and have been going through and removing older preview (master) builds, though it's possible some people have still got references to these versions if they needed early access to a feature.

Our expected usage going forward is around 18GB per year.

### How large is each release?

Each release is a single tarball which is just under 50 MB

### How frequently do you make a release?

We've started moving to 1 nightly release per day, plus aiming at 1 weekly minor version release.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @danielrbradley :wave:
Sorry for not getting back to you before. Thanks for  sharing a detailed description of the issue. I would like to know if you are OK with following a more incremental approach, and increase the project limit on a yearly basis, for example.
Maybe now, since you are hitting 10G limit, we could do 30G and next year we see how everything is going on. Would you be OK with that?

**Comment by danielrbradley** [comment]
Sounds great thanks! The form just looked like it was increments of 100, but 30 should be good for the next year.

**Comment by cmaureir** [comment]
Cool! 
I've set the upload limit for `pulumi-azure-native` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
