### ISSUE TITLE
File Limit Request: NDETCStemmer - 700 MB

### ISSUE THREAD

**Issue by alifadwitiyap** [pypa/pypi-support#2078]
### Project URL

https://pypi.org/project/NDETCStemmer

### Does this project already exist?

- [X] Yes

### New Limit

700

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Library for word stemming in Indonesian using the Nondeterministic Context method. This is my first time to register my project in pypi. If there any suggestion to shrink my project feel free to suggest.

### Reasons for the request

i have large word2vec model its take 650 MB, its make me need 700 MB size limit because i will update that model and i need more space to add more rules to stemmer in the future

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @alifadwitiyap :wave:
thanks for the detailed explanation. Due to the volatile nature of virtual environments (in the workflows I'm familiar with) I found it's complicated to download a 700M wheel many times. Some modules I have seen, offer an API to `download` the data and place it on a common directory, so independently of the vritual environment where the package is installed, they have the data. 
You an look at what `nltk` does: https://www.nltk.org/data.html

Let me know what you think about this approach.
Have a nice Sunday

**Comment by alifadwitiyap** [comment]
Thank you for your response. I followed your advice, and it solved my problem.
