### ISSUE TITLE
File Limit Request: rgb-lib - 250 MB

### ISSUE THREAD

**Issue by zoedberg** [pypa/pypi-support#2228]
### Project URL

https://pypi.org/project/rgb-lib/

### Does this project already exist?

- [X] Yes

### New Limit

250 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The [project](https://github.com/RGB-Tools/rgb-lib-python) is very new, it's a binding of a Rust library, [rgb-lib](https://github.com/RGB-Tools/rgb-lib), generated using [uniffi-rs](https://github.com/mozilla/uniffi-rs).

### Reasons for the request

The file that is exceeding the limit is a `.so` file generated by `cargo`. I cannot reduce its size and I expect it to increase in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nicbus** [comment]
Building the package with an older rust version (1.59) instead of stable (1.63 as of writing) I was able to produce a smaller package, enough to have the publishing work (just released version 0.1.1).

As far as I understand from this result, the limit is not enforced on the uncompressed files (e.g. the .so file) but on the compressed files that are uploaded when publishing (namely, the .tar.gz and .whl files).

If that's correct, I guess there's no need to raise the limit as high as 800MB, a smaller size could do as well. At the moment the wheel is 99MB if built with rust 1.59 or 110MB if built with rust 1.63, so I guess that raising the limit to 250MB should be enough to cater for future uploads, at least for some time.

If everything above is correct, please change the limit request to whatever value looks sensible in your opinion, as my 250MB estimate is just a guess.

**Comment by cmaureir** [comment]
Hello, thanks for the detailed report and analysis :+1: 
I've set the upload limit for `rgb-lib` to 300 MB only on PyPI, the project doesn't exist on TestPyPI, if you create it in the future and require some size increase, please file another report :)
Be mindful of the frequency of releases at that size.
Have a nice week!
