### ISSUE TITLE
Increase size limit for Tensorflow GPU related packages

### ISSUE THREAD

**Issue by av8ramit** [pypa/pypi-support#224]
Hi @dstufft or @di , I'm an engineer on TensorFlow. I was wondering if it would be possible to get a size increase for the following packages on upload.pypi.org/legacy/ and test.pypi.org/legacy/? This is preventing us from releasing binaries with even more compute capabilities.

We have deleted all stale packages of tf-nightly* before February 2020 in an effort to ease the size burden. 

Apologies if this is the wrong place to put this request. 

```
tensorflow 750MB
tf-nightly 750MB
tensorflow-gpu 750MB
tf-nightly-gpu 750MB
```

Thanks!

**Comment by ewdurbin** [comment]
Thank you for removing stale nightly releases. Continuing to do so would be greatly appreciated.

Limit increased. We are currently working on developing new guidelines around project storage limits on PyPI due to bandwidth consumption, for the time being **please limit the number of releases and files that you create with this limit**.

PyPI admins are actively working on our bandwidth consumption concerns and will be in contact with all projects that may be impacted by new project storage limits when we have the necessary tools and guidelines in place.
