### ISSUE TITLE
PEP 541 Request: html5lib

### ISSUE THREAD

**Issue by hugovk** [pypa/pypi-support#227]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/html5lib

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/hugovk

**Reasons for the request**

The project appears to have been abandoned.

* Last release: Dec 2017 https://pypi.org/project/html5lib/#history

 The last commit was in October 2019 but there's been no reply about a new release since May 2018.

The library will break in Python 3.10 due to the `collections.abc` deprecation removals.

It is used by many projects, for example it's vendored by pip (itself vendored in CPython's ensurepip module), by Bleach, and blocks Poetry running on new Python with the removal.

Due to the lack of release, the `collections.abc` deprecation removal was delayed from CPython 3.8 to 3.9, and this week has since been delayed again to 3.10. I expect the problem to resurface when work begins on 3.10 in or around May 2020.

In May 2018, @pganssle requested a new release. In December 2019, @vstinner emailed the maintainers @jgraham or @gsnedders, and has had no reply:

* https://github.com/html5lib/html5lib-python/issues/419

**Maintenance or replacement?**

Maintenance from a fork: https://github.com/html5lib-python/html5lib-python. I've commented on open PRs and approved some. I've merged those to my fork, and would plan a release to unblock the `collections.abc` issue, and appoint other community maintainers.

**Contact and additional research**

No replies to https://github.com/html5lib/html5lib-python/issues/419 or to Victor's email.

**Comment by jamadden** [comment]
@gsnedders has begun [responding to the issue](https://github.com/html5lib/html5lib-python/issues/419#issuecomment-591039618) in the project repo after this request was entered, so I think this can be closed.

**Comment by hugovk** [comment]
Yes, good news, we don't need this now. Thanks all!

**Comment by jayaddison** [comment]
From my (limited) perspective there's been a good resurgence in activity on `html5lib` during the summer thanks to the work of @gsnedders.  That said I still have concerns that the library may be encountering some difficulties maintaining review, improvement and release momentum.

Perhaps that's fine since `html5lib` is vendored within `pip` and thus stability is of very high importance, but other projects do manage to retain velocity while retaining safety.  It's possible `html5lib` could benefit from some kind of support community.

**Comment by mgorny** [comment]
@hugovk, do you happen to be still interested in this? `html5lib` is unmaintained again, and now `html5lib-modern` fork has sprung (which is basically a one-time bugfix rather than something intended for long-term maintenance, see RDFLib/rdflib#2935) which is causing problems for packaging now. It would really be preferable to have a maintained first-party `html5lib`, so people wouldn't be working around its lack of maintenance.
