### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BiBzz** [pypa/pypi-support#2271]
### PyPI Username

BiBzz

### Reason for request

Hey there!

Sorry to bother you with this silly issue but I've lost access to my previous phone 2FA authentication app.

I'm open to give you all the account proof that I can.

Have a nice day

Alex

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by BiBzz** [comment]
Thanks a lot @ewdurbin!

All's good now, password and 2FA have been reset and recovery codes stored.

Thanks again, have a great day.
