### ISSUE TITLE
Request trove classifier: matplotlib

### ISSUE THREAD

**Issue by story645** [pypa/pypi-support#232]
### The name of the classifier you would like to add

- `Framework :: Matplotlib`

### Why do you want to add this classifier?
Matplotlib has an ecosystem of domain specific libraries built on top of it, some of which are listed on our [3rd party package page](https://matplotlib.org/thirdpartypackages/index.html). We believe a classifier would help with discoverability of these packages, as the current system of modifying that one page in the docs has become unwieldy. `'Topic :: Visualization` does not fulfill this need as there are many non-matplotlib visualization packages. 

cc: @tacaswell

**Comment by story645** [comment]
Also want to xref against #139 because it highlights maybe whether framework even makes sense for most of the scientific tools...

**Comment by jamadden** [comment]
Hi! Thanks for the well written request. The PyPI moderators are in the process of developing a few guidelines for the creation of new `Framework` classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, I think we're expecting the bar to add new ones to be relatively high. Currently, we're looking at these guidelines:

* New `Framework` classifiers should be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that; the information you've already provided goes a long way towards satisfying that.

As to the other guideline ('immediate use to existing projects'), it's been suggested that the best way to demonstrate immediate use would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier. Help gathering those comments is appreciated.

**Comment by eric-wieser** [comment]
I'd be fine with including the classifier on [`mpl_toolkits.clifford`](https://github.com/pygae/mpl_toolkits.clifford) if it were to exist.

**Comment by anntzer** [comment]
I would add it to https://pypi.org/project/mplcursors/ and https://pypi.org/project/mplcairo/.

**Comment by dopplershift** [comment]
I would add it to https://pypi.org/project/metpy if it existed.

**Comment by jbednar** [comment]
I would add it to https://pypi.org/project/holoviews/ if it existed.

**Comment by philippjfr** [comment]
I'd also add it for https://pypi.org/project/geoviews/

**Comment by thewtex** [comment]
I would add it to https://pypi.org/project/itkwidgets/ if it existed.

**Comment by kmuehlbauer** [comment]
I would add it to https://pypi.org/project/wradlib

**Comment by tacaswell** [comment]
I would add it to https://pypi.org/project/GraVE/

**Comment by joferkington** [comment]
Likewise, I'd add it to https://github.com/joferkington/mpldatacursor and https://github.com/joferkington/mplstereonet if it existed.

**Comment by pradyunsg** [comment]
Thanks everyone for the comments!

I've gone ahead and added the `Framework :: Matplotlib` classifier to [PyPI](https://pypi.org/search/?c=Framework+%3A%3A+Matplotlib) and [TestPyPI](https://test.pypi.org/search/?c=Framework+%3A%3A+Matplotlib). :)

**Comment by DanielGoldfarb** [comment]
@pradyunsg  - Awesome.  Thank you very much!  (I will be adding to https://pypi.org/project/mplfinance/ )

**Comment by has2k1** [comment]
Great. I will add it to https://pypi.org/project/plotnine/.
