### ISSUE TITLE
File Limit Request: torch - 1000 MB

### ISSUE THREAD

**Issue by seemethere** [pypa/pypi-support#2341]
### Project URL

https://pypi.org/project/torch

### Does this project already exist?

- [X] Yes

### New Limit

1000

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

https://pytorch.org

### Reasons for the request

We have upgraded CUDA versions to 11.7 and with that the binary size of `torch` has grown to 850+MB, in order to continue to support releases on PyPI We're requesting a limit increase to 1000MB in order to avoid having to request size increases in the future.

We're anticipating that CUDA support will continue to be important to multiple users so the size increase should be a net benefit to consumers on the PyPI platform for those who would like to use PyPI as the dependency platform for their machine learning systems.

Related issues: https://github.com/pytorch/pytorch/issues/53336

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by seemethere** [comment]
cc @di

**Comment by rgommers** [comment]
The PyTorch 1.13.0 release came out 3 days ago and had `manylinux1` wheels of ~890 MB, so it looks like someone bumped the limit (thank you!).

Let me add a bit of context for the request:
- The 1 GB requested here is what was declared the max file size limit that PyPI maintainers are willing to support in https://discuss.python.org/t/what-to-do-about-gpus-and-the-built-distributions-that-support-them/7125
- For a long time PyTorch was stuck on CUDA 10.2, because the CUDA 11.x wheels ended up being in the 1.2-1.3 GB size range
    - The 11.x wheels were hosted on wheelhouses like https://download.pytorch.org/whl/cu116
    - The PyTorch team did significant work to decrease the wheel sizes as much as possible
- The manylinux standard and `auditwheel` didn't allow not bundling in some large shared libraries
    - An `auditwheel` `--exclude` option to exclude libraries (so package authors can put those in separate wheels if they really have to) was finally merged last week: https://github.com/pypa/auditwheel/pull/368, so it may be possible in the future to unbundle the PyTorch wheels a bit. This is not recommended still, and technically does break the manylinux spec - but the understanding is that package authors are allowed to take that responsibility.

It seems like a change was made; it'd be great to have that made "official" by closing this issue and commenting on the new limit.

**Comment by cmaureir** [comment]
Hey @seemethere and @rgommers thanks for the detailed explanation.
I've set the upload limit for `torch` to 1000 MB on PyPI. Please be mindful of the frequency of releases at that size.
