### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JoaquinSeguElli** [pypa/pypi-support#2476]
### PyPI Username

joaquin.segura.ellis

### Reason for request

Hello, I lost 2FA authentication app, because my mobile phone was stolen, on 14 December 2022 at midnight local time (Córdoba, Argentina). This is for both, PyPi and TestPyPi.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account on pypi.org, 2FA has been reset and a password reset issued on both pypi and testpypi, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
