### ISSUE TITLE
gbm-drm-gen 150MB

### ISSUE THREAD

**Issue by grburgess** [pypa/pypi-support#255]
**Project**
gbm-drm-gen
https://pypi.org/project/gbm-drm-gen/
-->

**Size of release**
The size of the project is 150MB  ie 90 MB over
-->

PyPi
-->

**Reasons for the request**
The project is a public response generator for the Fermi GBM satellite and the response data base must be packaged with the release.

If you expect your release sizes to increase in the future, mention it here.
-->
This may increase with new releases of the database

**Comment by ewdurbin** [comment]
Limit increased. We are currently working on developing new guidelines around project storage limits on PyPI due to bandwidth consumption, for the time being please limit the number of releases and files that you create with this limit.

PyPI admins are actively working on our bandwidth consumption concerns and will be in contact with all projects that may be impacted by new project storage limits when we have the necessary tools and guidelines in place.

**Comment by grburgess** [comment]
Thank you. Should I remove non needed releases to keep the storage down?

**Comment by ewdurbin** [comment]
@grburgess doesn't look like anything that's been uploaded thus far is of concern, so at this point there's really nothing needed from you.
