### ISSUE TITLE
PEP 541 Request: curve

### ISSUE THREAD

**Issue by jpcaram** [pypa/pypi-support#277]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/curve

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/jpcaram

**Reasons for the request**
Abandoned and invalid. Not owner, description, etc.

**Maintenance or replacement?**
Replacement with https://bitbucket.org/jpcgt/curve/src/master/

**Contact and additional research**
No valid owner. I even looked in the source files of the one and only release: There is nothing that identified the owner, project, company or web page.

**Comment by yeraydiazdiaz** [comment]
Hello @jpcaram. While it's true the project has no description and appears abandoned there is some code in it so we cannot proceed immediately with the transfer.

The user does have an email address associated with their account so I've emailed them, hopefully we'll hear back soon, otherwise we will proceed to declare the project as abandoned.

**Comment by jpcaram** [comment]
Hi Yeray,
Can we move forward with the transfer?
Thanks!

**Comment by yeraydiazdiaz** [comment]
Hello @jpcaram, I have not received response from the owner so the project is now considered abandoned.

I will now ask an admin to perform the transfer for you.

**Comment by ewdurbin** [comment]
transfer complete.
