### ISSUE TITLE
Limit Request: tensorflow_cpu & tf_nightly_cpu - 250MB

### ISSUE THREAD

**Issue by av8ramit** [pypa/pypi-support#284]
**Project**
tf_nightly_cpu
tensorflow_cpu

**Size of release**
250MB

**Which indexes**
PyPI

**Reasons for the request**
We are adding more code and headers into our CPU package. We expect the size to slowly increase over time.

**Comment by ewdurbin** [comment]
Current limit for both are 150MB, and largest release file is 147MB (tf_nightly_cpu-2.2.0.dev20200323-cp37-cp37m-manylinux2010_x86_64.whl).

Is a 100MB jump expected imminently? This really isn't a problem for the mainline releases, but nightlies of this size do become problematic overtime.

For the time being, the 250MB limit has been applied.

We are currently working on developing new guidelines around project storage limits on PyPI due to bandwidth consumption, for the time being please limit the number of releases and files that you create with this limit.

PyPI admins are actively working on our bandwidth consumption concerns and will be in contact with all projects that may be impacted by new project storage limits when we have the necessary tools and guidelines in place.
