### ISSUE TITLE
PEP 541 Request: shark

### ISSUE THREAD

**Issue by KrishKasula** [pypa/pypi-support#302]
**Project to be claimed**

`shark`: https://pypi.org/project/shark

**Your PyPI username**

`VijayaKrishnaKasula`: https://pypi.org/user/VijayaKrishnaKasula

**Reasons for the request**

There is no project page with that name on PyPi. Yet, I am unable to upload or use that project name.

**Maintenance or replacement?**

Replacement

**Contact and additional research**

No project page found. Hence, unable to contact the owner.

**Comment by jamadden** [comment]
That project exists but has no releases, qualifying it as invalid. I've sent a courtesy notification to the email address registered to the project owner. If we hear no objections after one week we can schedule a transfer.

**Comment by bikeshedder** [comment]
> I've sent a courtesy notification to the email address registered to the project owner.

I'm sorry. I didn't receive a single one of those.

Shark is a billing application based on Django: https://bitbucket.org/terreon/shark/src/master/

It is still actively developed but I have not yet made a release yet.

If it makes anyone happy I can release that code as 0.1.0 to pypi. It does in fact work - it's just not something I'd call release worthy.

**Comment by bikeshedder** [comment]
I pushed the current code as `0.0.1` to pypi.

Sorry for the delay. I really should have done that ages ago. :flushed: 
I also moved the repository to my GitHub account https://github.com/bikeshedder/shark

**Comment by jamadden** [comment]
@bikeshedder Thank you for your reply. (I emailed you at your registered PyPI email address, `<firstname>.<lastname>@t<elided>.de`. You might check that it's still valid.)

@KrishKasula Since the project has activity and the project owner has uploaded a release, this no longer qualifies as invalid. The project owner has also expressed the fact that the project is actively developed, so I can't see that this can be subject to PEP 541. Good luck finding a different name!
