### ISSUE TITLE
PEP 541 Request: shakti

### ISSUE THREAD

**Issue by Dhanush123** [pypa/pypi-support#303]
**Project to be claimed**

`shakti`: https://pypi.org/project/shakti/

**Your PyPI username**

`dhanushp`: https://pypi.org/user/dhanushp/

**Reasons for the request**

I believe this request is justified because the project appears to be abandoned after having been published on 2/13/20 with no (functional) code in the published pip package. I also can't find a GitHub repo for the package that would show work is being done on it. Finally, there is no contact information I can use to contact the author that can be found in their PyPI profile, GitHub profile, or pip package code.

**Maintenance or replacement?**

Replacement: I have been actively committing to a repository I created since 1/19/20 https://github.com/Dhanush123/shakti that I want to publish under the shakti package name instead.

**Contact and additional research**

See last sentence of "Reasons for the request". Also elaborating on that, I couldn't find any contact info in the package code or GitHub READMEs of other pip packages this owner has with functional code in them.

**Comment by jamadden** [comment]
That project appears to qualify as an invalid project under the PEP 541 rules. The owner appears to be @YoSTEALTH on github. The PyPI moderators have a policy of giving a one-week courtesy window where the owner of an invalid project is notified and can comment before an invalid project is removed/transferred.

**Comment by YoSTEALTH** [comment]
Its common for people to secure the project name while the project is under development!

Sorry, you will have to find another name.

**Comment by jamadden** [comment]
Under PEP 541, a project that "is name squatting (package has no functionality or is empty)" like this project, "is considered invalid and will be removed from the Index." 

This package currently fits the definition of a name squatting, invalid project. The week's notice is to allow the owner of such a project time to actually upload a functional, non-empty project, or to supply information under the [intellectual property policy](https://www.python.org/dev/peps/pep-0541/#id28) that would otherwise prevent a transfer. There is currently no mechanism to reserve a name for an indefinite period of time.

**Comment by jamadden** [comment]
Just within the one-week window a minimal project was uploaded to https://pypi.org/project/shakti/. (Even though it specifies a `python_requires` of an unreleased version of Python — 3.9 — I think it still has to count.) That resets all the timers and this project cannot be considered for transfer at this time.
