### ISSUE TITLE
Issue: Limit Request: NREL-rex - 250 mb

### ISSUE THREAD

**Issue by MRossol** [pypa/pypi-support#395]
**Project**

NREL-rex
https://pypi.org/project/NREL-rex/

**Size of release**

250MB

**Which indexes**

PYPI

**Reasons for the request**

This package provides tools to extract data from NREL's high-value resource Datasets [WIND Toolkit](https://www.nrel.gov/grid/wind-toolkit.html) and [NSRDB](nsrdb.nrel.gov). We use scipy.spatial.cKDTree's to map user-defined coordinates to sites in the datasets. Building the trees is computationally expensive and slow so we have pre-built them and want to release them with the package, but they exceed the 60mb size limit. Having the pre-built trees makes the code orders of magnitude faster for users.

**Comment by jamadden** [comment]
Does the data vary as frequently as the code or is it largely independent? If it's independent, has the possibility of distributing the data in a separate location, even a separate PyPI distribution, been considered? A 250MB file is a large upload and has costs for PyPI and its mirrors and CDN, and this project has created 13 releases since April. If those were all 250MB that would be a lot of bandwidth for PyPI and its users. But if the data were an independent package it's possible that it would have only been uploaded once?

**Comment by MRossol** [comment]
@jamadden the 250mb of zipped data is updated much less frequently than the code. Can you provide an example of how we could distribute the data in a separate distribution but then source it in the code-base?
Thanks

**Comment by jamadden** [comment]
If you were to publish the data on PyPI, you'd simply package it like normal package data. In the project that needs to use it, you'd list that project as a dependency, and then you'd use `pkg_resources` or [importlib.resources](https://importlib-resources.readthedocs.io/en/latest/) to gain access to its data files.

But I'll quote a senior PyPI moderator as saying that "PyPI isn't really intended for distributing large data sets", though, so that course of action isn't particularly encouraged. (However if it truly stays that size and changes rarely, it's small enough that the current moderator guidelines would approve it.)

Some projects instead host the data file on an HTTPS site they have control over, and provide a mechanism for their package to download that data on demand; some projects choose to have a way to check for updates, etc, but some other projects just change the URL and publish a new version of the Python package. The standard library is often sufficient for this task. 

Some projects just ask the end user to perform the download and place the data in a convenient location and let the library know where that is.

**Comment by di** [comment]
Closing due to lack of response.
