### ISSUE TITLE
PEP 541 Request: build

### ISSUE THREAD

**Issue by arunchandarQA** [pypa/pypi-support#413]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/build/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/arunchandar
(I am not the maintainer)

**Reasons for the request**

There was a PyPI package with the same name until 25 May. Our code base relies on that package. Now it has been replaced with another package with the same name.
I think PyPI should check if there are recent downloads before replacing the package.

**Maintenance or replacement?**

I can maintain the project if recovered.

**Contact and additional research**

**Comment by yeraydiazdiaz** [comment]
Hello @arunchandarQA, the project was removed by the author, not replaced via a PEP 541 request.

As you can imagine we cannot prevent owners from deleting their projects, however there are several warnings in place in PyPI advising of the consequences of removing the project. In this case the owner decided to go ahead anyway and another user has taken up the name.

I'm closing your request because the new project is literally a day old and it's not in the spirit of PEP 541 to monitor these cases.

If you really would like to maintain `build` I suggest you find the original repository, fork it, and publish it under a new name.

Best of luck.
