### ISSUE TITLE
Suggestion: Remove https://pypi.org/project/pprint/

### ISSUE THREAD

**Issue by stdedos** [pypa/pypi-support#419]
In accordance to https://test.pypi.org/help/#project-name
> ![image](https://user-images.githubusercontent.com/133706/83068869-a8aed480-a071-11ea-8fe6-2db79ff7303c.png)
>
> Why isn't my desired project name available?
> Your publishing tool may return an error that your new project can't be created with your desired name, despite no evidence of a project or release of the same name on PyPI. Currently, there are three primary reasons this may occur:
> 
> The project name conflicts with a Python Standard Library module from any major version from 2.5 to present.
> The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.
> The project name has been registered by another user, but no releases have been created.

I suggest that project https://pypi.org/project/pprint/ is removed. As you can see from the artifact, there is no useful code in any case.

You may or may not choose to _archive_ it, but at least don't satisfy it as a `pip install pprint` package.

**Comment by danielunderwood** [comment]
I was just looking at this project and was going to open an issue with the same suggestion. In addition to what you mentioned around not having it as `pip install pprint`, it seems to also be an invalid name according to [PEP-541](https://www.python.org/dev/peps/pep-0541/#invalid-projects):
> project is name squatting (package has no functionality or is empty);

The [repo for this project](https://github.com/hamadi15/test) seems to not have any content and also doesn't match the contents of the package tar. The only content there aside from boilerplate seems to be in `heloworld/__init__.py`:

```python
def tryprint():
    return ('it will be oke')
```

This project name is particularly bad since it is the name of a common python built-in. I managed to find this due to a project that listed pprint as part of its requirements.

**Comment by hugovk** [comment]
https://pypistats.org/packages/pprint

> Downloads last day: 4,183
Downloads last week: 22,500
Downloads last month: 97,040

**Comment by pradyunsg** [comment]
Sounds reasonable to me. Any thoughts @pypa/pypi-moderators?

**Comment by ewdurbin** [comment]
Done, thanks for the legwork.

![5B33AC5D-4241-4065-9F9E-69AAB8ED3127](https://user-images.githubusercontent.com/1200832/90316192-8b5e0980-deee-11ea-8685-73498db218eb.jpeg)
