### ISSUE TITLE
Limit Request: casadata - 400MB

### ISSUE THREAD

**Issue by vsuorant** [pypa/pypi-support#422]
**Project**

https://pypi.org/project/casadata/

**Size of release**

400MB

**Which indexes**

PyPI
**Reasons for the request**

casadata is a minimum data set for CASA (https://casa.nrao.edu/). Even though this is large package, we can remove the old versions whenever a new version is available.
The package size may increase over time but should do so very slowly (perhaps 10s of megabytes per year).

**Comment by jamadden** [comment]
Because distributions that large produce a poor installation experience for end-users, and because they place a burden on PyPI, its mirrors and CDN, moderators are encouraged to help packagers find alternate solutions. Some options include:

- break the package into smaller packages that depend on each other as necessary
- side-load large models or datasets via downloads from elsewhere at runtime/installtime.


I notice that side-loading of data seems to be available already. Perhaps that could be done automatically at install time, or when first used, or made into a function users explicitly call? Has anything like this been considered?

**Comment by vsuorant** [comment]
Splitting the package doesn't make much sense as the application requires all of the data to start up. We can have most of the versions in our own artifactory  but it would be beneficial to our non-expert users to be able to simply download the data as a dependency directly from PyPI.

**Comment by di** [comment]
I've set the upload limit for `casadata` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.
