### ISSUE TITLE
Issue: Limit Request: pyanthem - 350MB

### ISSUE THREAD

**Issue by nicthib** [pypa/pypi-support#464]
**Project**

pyanthem

**Size of release**

350MB

**Which indexes**

PyPI

**Reasons for the request**

This package include 350 MB of .ogg audio files. Compressed, this takes up a little over 300 MB, so I put the limit at 350MB to be safe.

While my package can operate without these files, it is much more useful with them, since a core functionality of it is creating synthesized audio (Without requiring an external program like fluidsynth)

**Comment by jamadden** [comment]
Because distributions that large produce a poor installation experience for end-users, and because they place a burden on PyPI, its mirrors and CDN, moderators are encouraged to help packagers find alternate solutions. Some options include:

- break the package into smaller packages that depend on each other as necessary
- side-load large models or datasets via downloads from elsewhere at runtime/installtime.

I notice that side-loading of data seems to be available already (`AE_download`). Perhaps that could be done automatically at install time, or when first used, or made into a function users explicitly call? Has anything like this been considered?

**Comment by nicthib** [comment]
It is currently how the package works (using GitPython). I was concerned that downloading files to a pip installation was bad practice, especially since they remain even after a pip uninstall. 

Increasing the limit is not imperative though, so I could keep things as-is.
