### ISSUE TITLE
Issue: Limit Request: Pifacecam - 150 MB

### ISSUE THREAD

**Issue by tensorfactory** [pypa/pypi-support#487]
**Project**
Pifacecam
https://pypi.org/project/pifacecam

**Size of release/project**
150 MB

**Which indexes**
PyPI

**Reasons for the request**
Need to use a larger model for better facial recognition accuracy.
Future releases sizes may increase in size as larger models are being developed.

**Comment by jamadden** [comment]
Hi and thanks for the request!

Before proceeding, I have a few questions and suggestions. First, the source distribution (sdist) currently on PyPI ([pifacecam-1.0.3.tar.gz](https://files.pythonhosted.org/packages/82/aa/e10f45bc4594f195746b06cdc715c794af929e023c70b699d80216209ba6/pifacecam-1.0.3.tar.gz)) is only 12k and doesn't include any source files. Likewise, the github repository linked [as the homepage](https://github.com/tensorfactory/PiFaceCam) doesn't contain any source files. Is there somewhere we can see the source files and build system? Can you update the sdist to include that?

Second, the binary wheel distributed on pypi as [pifacecam-1.0.3-py3-none-any.whl](https://files.pythonhosted.org/packages/c8/ff/ff09b0595f9d8680ca43643d79f48b8df5e8d67325b6126f89e93841d85e/pifacecam-1.0.3-py3-none-any.whl) contains `pifacecam/pifacecam.so`, a 32MB, 32-bit ARM binary, but the wheel tags (`py3-none-any`) specify that this is a non-native, pure-Python, wheel that will run on *any* system with Python 3. That situation can be confusing for end users and package installation tools. In the future, it's possible that PyPI will validate the wheel tags against the contents and reject wheels that have incorrect tags like this.  The manylinux1, manylinux2010 and manylinux2014 tags don't support 32-bit ARM platforms, but I *think* that [PEP600's rolling manylinux tag](https://www.python.org/dev/peps/pep-0600/) should, so to continue distributing binary wheels on PyPI it's probably important to switch to building with that PEP in mind. 

The reason I asked about source distributions is because there are package indexes specifically for Raspberry Pi wheels, which sidestep all of the problems with tags and distributing binary wheels on PyPI. https://www.piwheels.org/ for example distributes binary wheels for Raspberry PIs and is automatically used on Raspbian. It even automatically builds them — you don't have to do anything. But you do [have to upload a working sdist to PyPI](https://www.piwheels.org/faq.html).

**Comment by tensorfactory** [comment]
Hi Jason,
	Thank you for your thoughtful suggestions and questions.
I am new to these python packaging/distribution processes. 
After spending hours Googling about how to tag wheel file, meaning of each tag and what should be the platform tag for Raspberry Pi OS, I managed to create a new wheel file named "pifacecam-1.0.5-cp37-cp37m-linux_armv7l.whl".
Hopefully this is meeting PyPi's requirement. If not, would you kindly point me to right direction?

Understand that there are much benefits of distributing together with the source files but unfortunately we are not able to release our source files.
I have also removed the (sdist tar.gz) file since it doesn't contain any source file.

Kindly feedback if I have missed anything.

Thanks

Rgds
KC Yee

**Comment by jamadden** [comment]
> I managed to create a new wheel file named "pifacecam-1.0.5-cp37-cp37m-linux_armv7l.whl". Hopefully this is meeting PyPi's requirement.

That matches the tags [piwheels uses](https://www.piwheels.org/project/gevent/) and is listed as a [valid tag in warehouse](https://github.com/pypa/warehouse/blob/bfba7ca3d5ac9db11e91f528f45718fa38123ee7/warehouse/forklift/legacy.py#L102-L120) so I think you should be good!

> we are not able to release our source files.

This is just one opinion, but it seems to me that since you list a proprietary license in your README and do not release source code, using `License :: Other/Proprietary License` would be more accurate than `License::Freeware` .

> I have also removed the (sdist tar.gz) file since it doesn't contain any source file.

Thank you. That, together with the wheel tag change, should prevent attempts to install it on platforms that are unsupported.

I've gone ahead and changed the upload limit.
