### ISSUE TITLE
Limit Request: tensorflow-rocm-enhanced - 200MB

### ISSUE THREAD

**Issue by parallelo** [pypa/pypi-support#49]
Hi,

We would like to host the ROCm-enhanced version of TensorFlow on PyPI.  

However, we hit the 60MB limit when trying to upload to test.pypi.org. In the meantime, we have created placeholder 0.0.1-versioned projects for tensorflow-rocm-enhanced on both Test PyPI and PyPI.

Details:

- Project name: tensorflow-rocm-enhanced
- PyPI links:  
   - https://pypi.org/project/tensorflow-rocm-enhanced
   - https://test.pypi.org/project/tensorflow-rocm-enhanced
- Size: 189 MB per whl initially, but could eventually be more
- Indexes: both Test PyPI and PyPI

For some context, the builds for tensorflow derivatives tend to be reasonably large. For example, the tensorflow-gpu package is in the range of 100-200+ MB.

Please let us know how to move forward.

Best,

Jeff

edit: 
CC'ing @sunway513

**Comment by sunway513** [comment]
Hi @di , gentle ping -- any updates?

**Comment by sunway513** [comment]
Hi @di , gentle ping -- any updates? Please help let us know if you need any further information to proceed with the request.

**Comment by ewdurbin** [comment]
Limit increased to 200MB. We are currently working on developing new guidelines around project storage limits on PyPI due to bandwidth consumption, for the time being **please limit the number of releases and files that you create with this limit**.

PyPI admins are actively working on our bandwidth consumption concerns and will be in contact with all projects that may be impacted by new project storage limits when we have the necessary tools and guidelines in place.

**Comment by parallelo** [comment]
Many thanks for the update and for increasing the limit.  We understand the bandwidth challenges and will act accordingly to limit the number of uploaded files.  Thanks again.
