### ISSUE TITLE
Issue: PEP 541 Request: python-openid

### ISSUE THREAD

**Issue by ziima** [pypa/pypi-support#496]
**Project to be claimed**

`python-openid`: https://pypi.org/project/python-openid/

**Your PyPI username**

`ziima`: https://pypi.org/user/ziima

**Reasons for the request**

I'm currently maintaining the project myself under name python-openid2 https://pypi.org/project/python-openid2/. I was able to get access to the original projects' github repository, but I couldn't found anybody who would still have access to PyPI account to transfer the project.

**Maintenance or replacement?**

I intent to continue the maintenance.

**Contact and additional research**

I've tried number of people from the community. I got access to github repository, but I'm stuck on PyPI.

**Comment by hugovk** [comment]
Looks like @tnarg is the maintainer of https://pypi.org/project/python-openid/ (same username and profile image).

**Comment by tnarg** [comment]
I do not have a way to recover the @tnarg pypi account as I no longer have access to the employer email address associated with the account.

**Comment by jamadden** [comment]
I don't see that email listed publicly on either the python-openid project page, or on the `tnarg` user profile page. It is listed in the PyPI user database. @tnarg, can you confirm what that email was? Have you attempted any activity with that account lately? If so, can you confirm what sort of activity and what IP address the activity came from? Feel free to email me directly at the email address listed on my GitHub profile if you don't want to share any of that here.

**Comment by jamadden** [comment]
After exchanging emails with @tnarg I'm convinced that the two accounts belong to the same person. @tnarg has indicated willingness to vacate the python-openid name. Usually, when we are in contact with the current owner of the name, we ask them to perform the transfer, but @tnarg no longer has access to the PyPI account.  I've verified that @ziima has contributed to the project, so I will ask the admins to perform a transfer (rather than asking for a password reset, unless @tnarg would prefer that).

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by ziima** [comment]
Thanks.
