### ISSUE TITLE
Security research packages removed

### ISSUE THREAD

**Issue by alex-birsan** [pypa/pypi-support#526]
Hello,

I noticed that all the packages uploaded by https://pypi.org/user/alexbirsan/ have been recently removed.

These packages were being used for legitimate security research, allowing me to uncover vulnerabilities in multiple organizations so far -- I can provide references if needed.

All of the organizations I am targeting have authorized the testing through their respective bug bounty programs, and I take multiple steps to ensure impact to third-parties is minimized.

What I'm trying to say here is, it is better for everyone involved if I own these package names.

That being said, what would it take for PyPI to welcome security research packages like that on the registry? Perhaps adding additional warnings to the README files, or changing the code a bit? I am open to suggestions and looking forward to reaching a common ground.

**Comment by di** [comment]
Hi @alex-birsan, thanks for reaching out.

Your packages were removed because they were typosquatting on a number of prominent, legitimate packages. PyPI does not permit typosquatting for any purpose: even with the best intentions, these packages are often fairly scary/worrisome for the average PyPI user. Not every user has the ability to determine whether the package is malicious or not, especially when the package is executing arbitrary commands, capturing information, and phoning home.

> What I'm trying to say here is, it is better for everyone involved if I own these package names.

We believe it's actually better if these package names were "owned" by PyPI itself. As-is, these package names are now permanently blocked and can never be used again.

> That being said, what would it take for PyPI to welcome security research packages like that on the registry?

I appreciate you trying to improve the ecosystem here. Ideally if you come up with more typo'd package names that might be accidentally used by your target organizations, you can let us know and we will permanently block them as well.

**Comment by alex-birsan** [comment]
Thanks for the quick reply @di 

I understand PyPI's policy on typosquatting, but none of the packages I am referring too were typo'd names. Some were indeed susceptible to being accidentally installed by some legitimate users (the tensorflow stuff), and I am perfectly fine with leaving those blocked.

But what about the others? Most of the package names I claimed later had no reason at all to be sought out by legitimate users.

> We believe it's actually better if these package names were "owned" by PyPI itself. As-is, these package names are now permanently blocked and can never be used again.

I actually have a counter-example here: As a result of my recent research on a single package name, an organization has been able to uncover a large misconfiguration spanning multiple other package names. If that one name had been blocked out, I wouldn't have been able to report the issue, and the organization would have still been completely vulnerable.

Thanks again,
Alex

**Comment by di** [comment]
> Most of the package names I claimed later had no reason at all to be sought out by legitimate users.

I think this probably reason enough to not have these projects on PyPI. Ultimately PyPI is a tool for distributing valid Python projects. It's not intended to be a security research tool, and the burden that packages like this place on the 100% volunteer group of folks maintaining PyPI is not worth it.

To give you some insight: I've already spent about an hour of my time dealing with fallout as a result of these packages, specifically communicating with users who accidentally installed one of them who are concerned and are considering it a security incident. It really places undue burden on us.

> I actually have a counter-example here: As a result of my recent research on a single package name, an organization has been able to uncover a large misconfiguration spanning multiple other package names. If that one name had been blocked out, I wouldn't have been able to report the issue, and the organization would have still been completely vulnerable.

I'm not sure I understand how this was possible, do you mean that the organization was attempting to install multiple packages that don't exist? Or is this because the organization is using a private index server, but their installer was preferring projects on PyPI if the package existed there?

**Comment by alex-birsan** [comment]
> I'm not sure I understand how this was possible, do you mean that the organization was attempting to install multiple packages that don't exist? Or is this because the organization is using a private index server, but their installer was preferring projects on PyPI if the package existed there?

The latter.

**Comment by di** [comment]
Ultimately if you are interested in protecting users from this kind of attack, there are better ways to do it that protect the entire ecosystem, not just a specific set of organizations with bug bounties.

One idea that has been floated before is automatically blocking any new project name that currently have a non-trivial amount of 404 requests served by PyPI for it (or at least requiring approval). This would easily identify internal-only project names like this and prevent them from being used maliciously.

If you're interested in contributing to that effort, I think first steps would be making a proposal to this effect in more detail on the corresponding issue here: https://github.com/pypa/warehouse/issues/4998.
