### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by srikapardhi** [pypa/pypi-support#550]
Request for account recovery.

## PyPI Username

`srikapardhi`

---

##  Reason for request

Reason:
Lost 2FA authentication app after phone format. Not able to recover 2FA accounts after phone format.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
