### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by filipetavares** [pypa/pypi-support#554]
Request for account recovery.

## PyPI Username

`fmt`

---

##  Reason for request

Reason:
I lost my backup password from my 2FA application. Thus I'm restarting all my accounts. I don't have any packages in this account, so you can either delete or reset the account. I just want to be able use my email in a pypi account.

Thanks for your help.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
