### ISSUE TITLE
PEP 541 Request: llvm-lite

### ISSUE THREAD

**Issue by seibert** [pypa/pypi-support#555]
**llvm-lite**
`PROJECT_NAME`: https://pypi.org/project/llvm-lite

**seibert**
`USER_NAME`: https://pypi.org/user/seibert

**Reasons for the request**

This project appears to be typo-squatting our project, `llvmlite`: https://pypi.org/project/llvmlite/
The contents of the `llvm-lite` 0.0.0 sdist appear to be a copy of the `llvmlite` source code from our 0.33.0 release.  (Notably, the package name inside the sdist is `llvmlite`, not `llvm-lite`.)

**Maintenance or replacement?**

We would like this project to be removed as it is a copy of the `llvmlite` project with no changes and has the potential to cause user confusion due to the nearly identical naming.

**Contact and additional research**

We don't see any evidence that the sdist contains malicious code, but are concerned about this project being a future security risk.

**Comment by jamadden** [comment]
It's possible but not likely that PyPI user `pysunny` (the onwer of `llvm-lite`) is github user @pysunny. Hopefully they'll see this notification and respond here, whether they are or are not that user. I've also emailed the verified address PyPI has on file for that user.

It's not clear to me that the `llvm-lite` project would constitute name squatting or otherwise be classified as invalid or abandoned (it was just uploaded two months ago), so under PEP 541, in the absence of contacting the project owner, `pysunny`, I see two possible recourses: 

1) Cite this project as [an invalid project](https://www.python.org/dev/peps/pep-0541/#invalid-projects) because it "violates copyright, trademarks, patents, or licenses;". 

I'm not qualified to judge that.

OR

2) (which is basically the same as the first) Cite this project for an [intellectual property violation](https://www.python.org/dev/peps/pep-0541/#intellectual-property-policy) and involve legal@python.org.

**Comment by jamadden** [comment]
The project owner of `llvm-lite` has removed the project. 

If you wish to claim that name, one good option is to upload a package to it that has a dependency on your desired package name.

**Comment by ruut835** [comment]
Hi Jamadden sorry for inconvenience, 
There is no intension to take package ownership, project was just published on pypi to understand pypi operations, I was forget to removed it from pypi that time. It was just learning purpose, project has been removed from pypi.
