### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by amckenny** [pypa/pypi-support#563]
Request for account recovery.

## PyPI Username

`amckenny`

---

##  Reason for request

Reason:
Had to factory reset my phone with the google authenticator app on it. Still have my pypi password and token if that's helpful/necessary.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
