### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JosiasAurel** [pypa/pypi-support#567]
Request for account recovery.

## PyPI Username

`JosiasAurel`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

I had uninstalled by error my 2FA client on my phone and that caused me to lose my code

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
