### ISSUE TITLE
PEP 541 Request: aurora

### ISSUE THREAD

**Issue by andykee** [pypa/pypi-support#609]
**Project to be claimed**

`aurora`: https://pypi.org/project/aurora

**Your PyPI username**

`andykee`: https://pypi.org/user/andykee

**Reasons for the request**
The project doesn't actually appear to exist anywhere.

**Maintenance or replacement?**
I intend to replace the package.

**Contact and additional research**

When I attempt to publish my own package under the `aurora` name, I get a 403 Client Error: The user 'andykee' isn't allowed to upload to project 'Aurora'. See https://pypi.org/help/#project-name for more information. The link indicates one of three things has happened:

1. The project name conflicts with the standard Python namespace.
2. The project name has been blacklisted
3. The project name has been registered by another user, but no releases have been created.

`aurora` is nowhere to be found in the Python namespace. I'm assuming the name is valid so #2 seems unlikely. This leaves me to believe #3 is the most likely issue.

**Comment by jamadden** [comment]
The project `aurora` had both of its releases removed in 2015 and has been dormant since then, making it an invalid project subject to removal/transfer.

@ak3n and @wickman appear to be the PyPI owners of that project. The PyPI moderators like to allow a one-week period between informing the owners of an invalid project that it will be removed and the actual removal. Accordingly, unless the project status changes, or @ak3n or @wickman perform the transfer themselves, project `aurora` will be subject to admin transfer after September 17.

Because versions 0.0.3 and 0.0.4 have been previously used, it won't be possible to upload releases with those versions.

**Comment by ak3n** [comment]
I have deleted the project. Feel free to reuse it.

**Comment by andykee** [comment]
Thanks so much @ak3n!
