### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by defntvdm** [pypa/pypi-support#628]
Request for account recovery.

## PyPI Username

`defntvdm`

---

##  Reason for request
Lost 2FA authentication app and security token

Reason:
I don't know how but I lost PyPi row from my Google Authenticator and then I didn't use keepass for storing my passwords and secret codes

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by defntvdm** [comment]
Thanks)
