### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by majabojarska** [pypa/pypi-support#644]
Request for account recovery.

## PyPI Username

`majabojarska`

---

##  Reason for request
Flashed new firmware on phone with 2FA authentication app, lost access to the authorized app.
Login and password are still valid. I have access to the account's email.
I never generated any recovery codes.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
