### ISSUE TITLE
PEP 541 Request: Pylon

### ISSUE THREAD

**Issue by mao-liu** [pypa/pypi-support#647]
**Project to be claimed**

`pylon`: https://pypi.org/project/pylon

**Your PyPI username**

`ch41rmn`: https://pypi.org/user/ch41rmn/

**Reasons for the request**

- This project has been abandoned, the last release is more than 10 years ago on python2
- The project homepage indicates the project is deprecated in favour of `PYPOWER` (https://pypi.org/project/PYPOWER/)
- The last release of PYPOWER was relatively recent (2018), however the PyPI project description indicates the original author is no longer actively maintaining this repository

**Maintenance or replacement?**

- We intend to publish a different package, https://github.com/intelematics/pylon-oss
- Our project is geared towards solving challenges for distributed data engineering and analytics workloads on cloud infrastructure, in a very light-weight and cost-effective manner. We began as an internal project 2 years ago.
- We will maintain past releases. Our first release will be 0.10.0, while the latest release for the current package is 0.4.4.
- We will provide references to past releases and `PYPOWER`, both in PyPI and our project README, for users who are looking for previous functionality.

**Contact and additional research**

We reached out to the original package maintainer on 2020-09-23. There has been no responses.

**Comment by yeraydiazdiaz** [comment]
Hi @mao-liu, also tagging GitHub user @rwl as the original author and current owner of the project.

While you are right that the owner clearly deprecated the Pylon project in favour of PYPOWER, [Pylon still is being downloaded](https://pepy.tech/project/pylon). Publishing a completely different project under the same name would cause these users code to break.

In light of this I do not think the transfer is the best course of action for the users of PyPI. I can only suggest looking for a different name for the project. Other moderators are welcome to express their views if they see otherwise.
