### ISSUE TITLE
Issue: PEP 541 Request: datafusion

### ISSUE THREAD

**Issue by jorgecarleitao** [pypa/pypi-support#659]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/datafusion

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/jorgecarleitao

**Reasons for the request**

* The only release contains only a dummy `__init__.py` without content
* The user has +500 projects on pypi with the same content, which suggests that it is a bot or otherwise abuse of the system.
* The provided email does not exist
* there seems to be no intention to be used

<img width="1126" alt="Screenshot 2020-10-10 at 16 52 13" src="https://user-images.githubusercontent.com/2772607/95658207-fad02e00-0b18-11eb-8d9a-cb2d0718e5cf.png">

**Maintenance or replacement?**

Since the project is just a dummy without functionality, this is a replacement, by https://github.com/jorgecarleitao/datafusion-python.

**Contact and additional research**

I tried to reach the author, but the provided email is not valid / does not exist.

**Comment by jorgecarleitao** [comment]
The release in test.pypi is available here: https://test.pypi.org/project/datafusion/

**Comment by jorgecarleitao** [comment]
Related to #536 , cc @ArnoCan

**Comment by ArnoCan** [comment]
Dear Jorge,
the project is a separate project providing a common platform for various data description syntaxes - e.g. JSON, XML, YAML, also INI/CFG/CONF, .properties, with additionals like ASN.1. So this is neither a dummy, nor spam. Due to my development approach which includes thorough documentation I required the names early, because simply using sed for working named does not work in any case and for any cross-refrence in hierarchical package dependencies, neither for development trees.

The longer time it took is due to the context of providing a complete framework, where this project is just a brick.

The update of datafusion and others is available within these days.

WKR

**Comment by ArnoCan** [comment]
Another hint for the number of projects.

The projects related to PyPA or setuptools are e.g.:
    setuplib + setuplibcore + setupdocx + setupjavax + setuptestx + setupbashx

These are logically grouped into the virtual packages - similar to e.g. PyWin:
   ictstacks:   which is the overall framework
   packageit: which groups the installer releated packages - here setuptools / distutils

This results in the logical/virtual package hierarchy for installation:
- itstacks -> packageit -> setupbashx
- itstacks -> packageit -> setupdocx
- itstacks -> packageit -> setupjavax
- itstacks -> packageit -> setuplib
- itstacks -> packageit -> setuplibcore
- itstacks -> packageit -> setuptestx

This already makes 8 packages - you can find the most of them already published, but not yet updated - which will be done soon.

So be sure that each package actually exists and supports Python2.7 + Python3.5+ on the platforms Linux, BSD, Unix, OS-X/macOS, and Windows(mostly from W2K on). Additionally OSs like Minix, RisOC(?) and for some OS-alike such as MicroPython.
So this requires a lot of adaptation, and even more tests.

Also to mention the basically required sophisticated document-automation to cope the mass of projects timely - which I had in addition to develop finally by myself.

This are some of the reasons for the delayed publishing.

WKR

**Comment by ArnoCan** [comment]
I do not agree to your interpretation, the project datafusion has functionality. As I listed before, If you have to write documentation and are developing cross-dependent packages you need a lot of actual references, which should not change.
Though you need reliable names - which require the preparation of the upload, though the creation of the package. A pretty natural and causal process.

1.  The PEP-541 says:
-  "(package has **no functionality or is empty**)"
    the project has functionality so do not match the cause.

2. The PEP-541 says:
-  "the project violates **copyright**, trademarks, patents, or licenses;
    The project-name-trolling would meet this cause, because I am as causal the pre-copyright owner.
    Thus the PEP-541 has at least this issue and prohibits in case of actual projects as this is the case it's aplication.

And to say it once again - honestly I am a bit astonished - the PEP-541 is not meant to troll project names by projects which decide to do so a week before!
- https://test.pypi.org/project/datafusion/#history (11 Oct. 2020)

The first set of relevant packages including "datafusion" will be published today on a number of repositories, so the proof is obvious.

But anyhow - this issue has to be closed in any case, because it is simply not a spam account. So I definitely reject the issue #659 as baseless - simply a mistake.

WKR

**Comment by jorgecarleitao** [comment]
This issue seems to have been resolved. Thank you to whoever did it (@pradyunsg ?)
