### ISSUE TITLE
Limit Request: paddlepaddle_gpu: 800MB

### ISSUE THREAD

**Issue by DDDivano** [pypa/pypi-support#663]
Project:
https://github.com/PaddlePaddle/Paddle
https://pypi.org/project/paddlepaddle-gpu/

Size of release/project

800MB

Which indexes

PyPI

Reasons for the request

We will release a new version for paddlepaddle_gpu recently. Our current size limit is 600M, and the dev version is 660M. Because a few new features are enabled in this version, and most of the new feature is new operate op (200 new api )with cuda and cudnn and the cuda c++ dll has a large size in windows , so the size increase quickly. Can you please help to increase this to around 800MB.

**Comment by zhouwei25** [comment]
@di  can you Deal with the problem, thank you very much!

**Comment by zhouwei25** [comment]
@di  can you Deal with the problem, thank you very much!

**Comment by di** [comment]
I've set the upload limit for `paddlepaddle-gpu` to 800 MB on PyPI.

This project is currently the 9th largest project on PyPI and is approaching it's 180GB total project size limit. It may be time to begin removing old releases if possible or putting some effort into shrinking the distribution size. We are unlikely to be able to raise the limit much higher in the future.

Also, _please_ do not make repeated comments or otherwise spam us with notifications on these issues. It does not help in any way whatsoever. If it continues in the future, we will not allow you to comment in this repository, please consider this a warning.
