### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by scjurgen** [pypa/pypi-support#676]
Request for account recovery.

## PyPI Username

`scjurgen`

---

##  Reason for request

Reason:
The email (scjurgen@yahoo.com) username (scjurgen) associated with my account seems to be broken (https://pypi.org/user/scjurgen/) 

Requesting a "password reset link" sends me an email to reset with the classic token. 
I can submit a new password, however the successive login with my username does not honour the new password. 
The email gives me strangely a link to test.pypi.org.

**Comment by ewdurbin** [comment]
It appears that the email associated with the `scjurgen` user on pypi.org is typo'd as `scurgen@yahoo.com` and thus password reset attempts are bouncing. I don't understand how you're receiving any emails with a password reset token.

Because Author Email metadata in all historic releases for projects owned by the user matches, I've updated the primary email address on the account and issued a password reset. You should be able to recover access via that mechanism now.

**Comment by scjurgen** [comment]
This worked, TY.
