### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by TonyMarkham** [pypa/pypi-support#678]
Request for account recovery.

## PyPI Username

TonyMarkham

---

##  Reason for request

Reason:
Lost 2FA authentication app or security token

**Comment by kirankotari** [comment]
+1 
I am facing the same issue. Phone has been formatted automatically lost all 2FA on device. Help session say to login via recovery codes, but I don't see such an option to click on login page. Is your system stable? on recovery process, Why it's not automated. 

username: kkotari

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
