### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by e-kirkland** [pypa/pypi-support#750]
Request for account recovery.

## PyPI Username

`eddie-k`

---

##  Reason for request

Reason:

I never setup two-factor authentication, and now I can't login without a two-factor code. I need to log in to generate those codes, so I'm stuck! Please help!! Thanks.

**Comment by ewjoachim** [comment]
I'm surprised that you're blocked by 2 factor auth if you never set it up ?
Our logs indicate that it was activated on `2020-10-10 13:39:44.874790` (2 minutes after creating your account) and your received an email titled `[PyPI] Two-factor method added`.

I understand that whether you activated 2FA or not will not solve the problem that you're currently locked out but I just want to make sure there's not some kind of strange bug that would have activated the 2FA without your consent. I would ask if anyone else has access to your account, but givent the 2FA was added just after the account was created, such a scenario would seem unplausible.

Have you double-checked on whatever TOTP application you have on your phone (e.g. Google Authenticator) if you wouldn't happen to have it configured by any chance ?

**Comment by ewdurbin** [comment]
2FA is definitely never configured without user action... But because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by e-kirkland** [comment]
Thank you, I apologize that I hadn’t responded sooner. I greatly appreciate you getting back with me to resolve this. Thanks to your team!
