### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dcebreros** [pypa/pypi-support#763]
Request for account recovery.

## PyPI Username

<dcebreross>
`dcebreross `

---

##  Reason for request

Reason:
Restart all applications from my phone.

**Comment by ewdurbin** [comment]
@dcebreros you need to provide your username on PyPI for this to be resolved.

**Comment by dcebreros** [comment]
Hello, my user name is: dcebreross

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
