### ISSUE TITLE
Limit Request: PySide6 - 200 MB

### ISSUE THREAD

**Issue by faltsi** [pypa/pypi-support#776]
**Project**
PySIde6

**Does this project already exist?**
Yes, see https://pypi.org/project/PySide6/

**Size of release/project**
Max wheel size will be 200 M

**Which indexes**
Increase is requested to PyPI and Test PyPI

**Reasons for the request**
PySide6 provides Python bindings for the Qt6.
Current wheel size exceed the 100M limit. Wheels do include Qt libraries to be deployed with the the Python API.

**Comment by cmaureir** [comment]
Just for the record, we had the same situation for PySide2 https://github.com/pypa/warehouse/issues/4089
Due to the name change, we needed to create a new project :dancers: 
Thanks :tada:

**Comment by ctismer** [comment]
I hope they will be reacting, soon.

**Comment by ediosyncratic** [comment]
Phrasing: 
> bindings for the Qt6.

should be either
> bindings for the Qt6 libraries.

or 
> bindings for Qt6.

**Comment by pradyunsg** [comment]
Seems legit: https://wiki.qt.io/Qt_for_Python_Development_Notes

Bumped the limit to 250 MB for PySide6 on both PyPI and TestPyPI.

**Comment by cmaureir** [comment]
@faltsi is the person behind every "Infra" section on that wiki page :D
Thanks @pradyunsg :tada: that was really fast!

**Comment by cmaureir** [comment]
Hey @pradyunsg sorry for pinging you directly,
we just had an issue while trying to upload the 6.2.0 release that includes more modules. Since the Qt 6.2 release also include universal binaries for macOS, we faced the problem that 250M is not enough, since the largest wheel we have is around 310MB, could it be possible to get an upgrade to 350-400 MB ?
Thanks for your time.
(In case I need to open a new issue, please let me know)

**Comment by cmaureir** [comment]
opened a new issue https://github.com/pypa/pypi-support/issues/1342
