### ISSUE TITLE
PEP 541: Request of package name 'better'

### ISSUE THREAD

**Issue by Kieran-Bacon** [pypa/pypi-support#78]
**Project**
`PROJECT_NAME`: https://pypi.org/project/better/
Github: https://github.com/CodyKochmann/better

**Username**
`USER_NAME`: https://pypi.org/user/Kieran-Bacon/

**Reasons for the request**
I believe that the project has been abandoned as no new commits have been made to the package in over 2 years. The package name doesn't property reflex its contents and it doesn't seem to be set up to able to allow for its future development. 

**Contact and additional research**
I've e-mailed the author requesting the name 10+ months ago and heard nothing in response. My e-mail read:
Hey,

I'm writing to request the package named 'better' that you've currently gotten ownership of on PyPi. I've written a package myself which I think the name suits rather well. 

I've seen that you haven't committed to your 'better' repository in some time, so I hope that you will be willing to give it up?

I'd be unbelievably grateful if you could

Kind regards,
Kieran Bacon

**Comment by jamadden** [comment]
Could you please provide the repository for your replacement project?

We have a verified email on file for the pypi user which matches the email address on the github profile. I've sent an email.

**Comment by CodyKochmann** [comment]
Hi. I apologize for not seeing the email you sent. I normally just keep an eye on the issues of all of my projects for stuff like this.

I dooo believe if this project's maintenance was a concern, it should have been raised in an issue. Other than the negative feedback I've gotten from many for even letting this repo exist, the only reason why I haven't committed to it is because helpful code snippets were almost always better suited to be put in a library that is more focused on those feature sets so their functionality can be demonstrated in a focused setting.

I was looking through the repo you're requesting the name to be transferred to. Its well organized and pretty solid.

If you do want those snippets to be almost completely ignored due to the arrogance and overgeneralization of the project's name and purpose, I believe we should work together to merge the two with a pull request since like you I wrote it to eliminate repetitive snippets that I write a lot. Otherwise, I recommend that you consider another name that people can discover since your repo seems to be well suited to be a solid async focused package.

I solely maintain a handful of pypi projects and hold onto this project to act as a living warning for others to avoid generalized names like this unless you don't want to be taken seriously by high assurance people (theres stories for that) and the feature literally has no other place to exist other than a package called `better`.

**Comment by jamadden** [comment]
Thanks for the reply. Since contact has been made, I don't see anything more for pypi-support to do here.
