### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tzachalon** [pypa/pypi-support#784]
Request for account recovery.

## PyPI Username

`tzachmona`

---

##  Reason for request

Reason:
didn't have recovery codes, and switched to a new phone.

**Comment by ewdurbin** [comment]
Because the only project associated with this user has no public source code repository accessible, which is usually used for verification, your only option is to have the User disassociated with that project to proceed. You can then request to be added back as an Owner/Maintainer.

If this is OK I can proceed to reset 2FA for your user.

**Comment by tzachalon** [comment]
Hey, I was just disassociated from all my projects. please remove my MFA @ewdurbin 

Thanks!

**Comment by ewdurbin** [comment]
Confirmed. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
