### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ApolloDS** [pypa/pypi-support#821]
Request for account recovery.

## PyPI Username

`ApolloDS`

---

##  Reason for request

Reason:

- I just created the account and the test account with 2FA. My Passwordsafe (Bitwarden) has lost the 2FA when I duplicated the entry for test.pypi.org, thats why I have not already created the recovery codes and cannot login anymore.
- Can you please reset my account or remove 2FA so that I can start again.
Thank you very much.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
