### ISSUE TITLE
Limit Request: apache-flink - 20GB

### ISSUE THREAD

**Issue by HuangXingBo** [pypa/pypi-support#831]
**Project**: https://pypi.org/project/apache-flink/

**Does this project already exist?**: Yes

**Size of release/project**: 20GB

**Which indexes** PyPI

**Reasons for the request**
We need to do releases for apache-flink 1.12.1 but we cannot upload packages as we have reached maximum project size(10GB).

Increasing the limit size to 20GB can allow us to continue to release several versions.

Thank you

**Comment by xintongsong** [comment]
Apache Flink 1.12.1 contains 9 artifacts (8 `.whl` files and 1 `.tgz` file). We hit the project limit after 7 artifacts being uploaded. There are still 1 `.whl` (209 MB) and 1 `.tgz` (207 MB) to be uploaded.

Considering future releases, more space would be needed. Increasing the project limit to 20 GB should work for the foreseeable releases.

We cannot remove files for the old releases, since there might be users still using them.

**Comment by xintongsong** [comment]
@di Could you help with this? Thanks

**Comment by di** [comment]
Please do not make repeated comments or otherwise spam us with notifications on these issues. It does not help the process  in any way whatsoever.

**Comment by di** [comment]
I've set the project size limit for `apache-flink` to 20 GB on PyPI.
