### ISSUE TITLE
PEP 541 Request: honeycomb

### ISSUE THREAD

**Issue by Geoiv** [pypa/pypi-support#832]
`PROJECT_NAME`: https://pypi.org/project/honeycomb

**Your PyPI username**
`USER`: https://pypi.org/user/nhdsdatasci

**Reasons for the request**
I believe the `honeycomb` project to be abandoned:
* The most recent release, version `0.2.3`, was released nearly 6 years ago.
* This is the only package on the author's account, so no adjacent author activity is visible
* The package's documentation is very sparse, and does not clearly indicate what the intended use/purpose of the package is.
* No home page or repository is provided

**Maintenance or replacement?**
As part of a data science/engineering team, I have developed a tool for facilitating and simplifying communication between a Python session and Apache Hive. The project has been in development for just under a year. It is still in active development, and my hope is that it may one day have a tangible user base. If the name transfer is successful, that project will be published under the transferred name.

Repository: https://github.com/neighborhoods/honeycomb
Collaborators & team members: @frankiezeager, @freytheviking

**Contact and additional research**
I have emailed the author at the address provided on the project page, and have received no response for over a week as of 01/15/2021. There does not appear to be any other contact information available for the author.

Author profile: https://pypi.org/user/honeyLee7/

**Comment by yeraydiazdiaz** [comment]
Hi @Geoiv, given you intend to fully replace the project we risk breaking its users code. I can see there are [some downloads](https://pepy.tech/project/honeycomb) so I tend to err on the side of caution and not proceed with the transfer.

Nevertheless, I will attempt contact with the owner in case they can shed some light on the actual usage of the package since it does reference a "honey" project but, as you mention, there is no homepage or documentation so it's hard to gauge the impact of the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
