### ISSUE TITLE
PEP 541 Request: ansible-test

### ISSUE THREAD

**Issue by webknjaz** [pypa/pypi-support#892]
**Project to be claimed**

`ansible-test`: https://pypi.org/project/ansible-test

**Your PyPI username**

`webknjaz`: https://pypi.org/user/webknjaz

**Reasons for the request**

The details are outlined here: https://github.com/nylas/ansible-test/issues/20.

But TL;DR — this project is abandoned and it ships the same script name `ansible-test` that ansible-core does. It is harmful because many people don't read the docs and attempt `pip install ansible-test` thinking that they need it and that messes up their systems or they get something that we tell to execute and it doesn't work. So it's almost like name squatting (but I don't think the original author intended to do any harm).

**Maintenance or replacement?**

Possible replacement. TBD. But we may also need to forbid using this name.

**Contact and additional research**

The dist doesn't have an email set in the metadata but I've attempted to raise this question in the repo that seems to be the source for that package: https://github.com/nylas/ansible-test. No response, though.

**Comment by webknjaz** [comment]
I saw that while I was typing in this request, Sorin also did the same (https://github.com/pypa/pypi-support/issues/891). He is an active Ansible community member. I'm from Ansible Core Engineering (Red Hat's team working on ansible-core) and also he tagged @gundalow who leads an Ansible Community team (also on Red Hat's payroll). Not sure which of the issues should survive :man_shrugging:

@mattclay any thoughts on `ansible-test`?

**Comment by mattclay** [comment]
The name collision is a source of confusion for users. I've had users asking for help on IRC with using `ansible-test`, only to find out they've installed the unrelated package from PyPI and now their installation of `ansible` or `ansible-base` has been partially overwritten.

**Comment by tadeboro** [comment]
To be fair, the `ansible-test` executable and `ansible_test` package only became part of Ansible in version 2.9.0, which was released in October 2019. The `ansible-test` package was released in May 2015, which is more than four years before Ansible started shipping the `ansible-test` executable. So if anything, Ansible stomped on an existing project's name.

I do agree that the situation is far from ideal, but taking the name away from the original author does not seem to be the right way of resolving this issue. The `ansible-test` project may not be actively maintained, but PyPI contains quite a few such packages and no one is trying to get them removed.

`ansible-test` is not the only ansible-prefixed PyPI project. There is also an `ansible-tests` project that might confuse people. Is that one also slated for termination because of its name? (And yes, that one also predates Ansible 2.9.)

**Comment by webknjaz** [comment]
The problem here is that many versions of Ansible already ship ansible-test (first implemented in 2016 but not exposed outside the repo until 2019). Even if we rename the executable, the end-users will keep hitting this problem for years to come.

Besides, looking at https://pypistats.org/packages/ansible-test, it seems like the only downloaders are PyPI mirrors, not real users. I bet it was created at Nylas, Inc. many years ago, was used internally for some time, and then got abandoned. Why should a project nobody cares about create problems for others?

**Comment by tadeboro** [comment]
> The problem here is that many versions of Ansible already ship ansible-test (first implemented in 2016 but not exposed outside the repo until 2019). Even if we rename the executable, the end-users will keep hitting this problem for years to come.

True, but it would be a bit dishonest to blame the original author for this situation since the Ansible project introduced the name clash. If they are willing to give up the name, great. But if not, then I would say Ansible needs to come up with a solution that does not require rewriting the history just because the current state is inconvenient for it.

> Besides, looking at https://pypistats.org/packages/ansible-test, it seems like the only downloaders are PyPI mirrors, not real users. I bet it was created at Nylas, Inc. many years ago, was used internally for some time, and then got abandoned. Why should a project nobody cares about create problems for others?

We have problems because the Ansible project did not do its due diligence before making an internal testing tool public. And to be completely honest, I do not remember the last time someone complained about this name clash. Both `ansible-test` executables are developer tools that regular users do not use. They are meant to be used by Ansible role developers (that already switched to using molecule for testing in most cases) and Ansible collection developers (that should know what tools they need).

This is why I feel that this name takeover is not justified. I would understand if the `ansible-test` project was just a placeholder or contain malicious content, but none of this is currently true. And again, we are talking about development tools, targeted at knowledgeable people that should know their way around the python ecosystem.

**Comment by yeraydiazdiaz** [comment]
I think the best move would be to place this project in the prohibited project name list, however, moderators don't have permissions to do so, only @pypa/warehouse-admins do.

**Comment by webknjaz** [comment]
I've just got another person on IRC confused why `pip install ansible-test` does get a promised `ansible-test` executable onto their machine.

What is the right install command?
============================

For people coming here from search, here's how to install the official `ansible-test` tool:
```sh
pip install ansible-core
```

**Comment by webknjaz** [comment]
@ewdurbin @di any help here?

**Comment by webknjaz** [comment]
Also, for the record, this summer we've got a DevTools team separate from the Ansible Core one. And some point the plan is to move it to a separate project. So it now seems okay to add this name to the block list but later we may need to use it, after all.

**Comment by ssbarnea** [comment]
I do support @webknjaz proposal and i hope we can sort it out as that publishing in particular does only seem like a namespace squatting (note the unknown name and invalid email).

@yeraydiazdiaz We would like to takeover the project not to ban it, especially as we would like to separate ansible-test from ansible-core anyway. Can you help or we need others from @pypa/warehouse-admins group for that? Thanks

**Comment by yeraydiazdiaz** [comment]
I've transferred the project to @webknjaz, let me know if you need any more help.
