### ISSUE TITLE
PEP 541: Transfer of ownership of namesquatted package "gitchart"

### ISSUE THREAD

**Issue by flashcode** [pypa/pypi-support#93]
**Project to be claimed**

`gitchart`: https://pypi.org/project/gitchart

**Your PyPI username**

`flashcode`: https://pypi.org/user/flashcode

**Reasons for the request**

The project on PyPI is a fork of my program `gitchart`. The author uses the same project name (which is a GPL violation), with a different version (0.0.3 while my current version is 1.4).

I contacted Thomas Grainger 2.5 years ago to remove this project and he refused, you can see the GitHub issue here: https://github.com/flashcode/gitchart/issues/5
He also created a GitHub organization to fool people using gitchart: https://github.com/gitchart/gitchart

So in my repository I added a big warning to let people know that the `gitchart` package on PyPI is a "fake and untrusted package": https://github.com/flashcode/gitchart#install

**Maintenance or replacement?**

As main author of gitchart, I'll maintain actively the `gitchart` project.
My repository is here: https://github.com/flashcode/gitchart

**Contact and additional research**

See: https://github.com/flashcode/gitchart/issues/5

**Comment by yeraydiazdiaz** [comment]
Hello @flashcode, since you have made contact with @graingert and I believe he's been active in this and other repositories that I know of he should be able to weigh in on this issue.

That being said and based on the conversation on https://github.com/flashcode/gitchart/issues/5 it seems this boils down to a disagreement between the two of you. We encourage PyPI users to have a dialog amongst themselves, it is not our role as moderators to arbitrate on these.

I encourage both parties to read [PEP 541](https://www.python.org/dev/peps/pep-0541/) in detail to further understand the process.

**Comment by flashcode** [comment]
@yeraydiazdiaz: thanks for the reply, I've already read the PEP 541, but unfortunately, as you can see in the issue mentioned, the dialog was not really possible with Thomas.

As I'm the author of the software I thought this was somewhat logical I could take the ownership of the PyPI project (in addition it seems to be abandoned, while I'm myself maintaining actively the software).

I understand this could be difficult for you to arbitrate, but I would be disappointed if I can't recover this project, and this is a problem for the users of PyPI: they're fooled with this project, which does not reflect mine, but uses the same name.

If Thomas really wants to distribute my software with changes (so, as a "fork"), I welcome that with another name, to prevent any confusion.

**Comment by yeraydiazdiaz** [comment]
It's been four weeks since the last update on this issue with no reply.

Given there has been no relesases or updates on https://github.com/graingert/gitchart since March 2017 and the download stats are quite low (18 in the last 31 days) I'm inclined to allow the transfer to @flashcode.

I will not immediately contact the admins to request a transfer in the hope that @graingert will reply to this issue in the next few days. It looks to me like he's moved on from `gitchart` anyway and we'd all much prefer a voluntary transfer rather than a forced one.

**Comment by graingert** [comment]
I wasn't aware that gitchart upstream had new changes. Happy to add @flashcode as a maintainer, not happy to add as owner as they have already stated their intention to remove the existing versions breaking current users

**Comment by yeraydiazdiaz** [comment]
As I mentioned above, the stats for `gitchart` are really low, 18 downloads in the last 31 days, so the argument of breaking current users is probably not that much of a problem and I'm sure they will not mind upgrading. Is there another particular reason you want to stay the owner?

Given he's the original creator of `gitchart` it seems fitting to me he would also be the owner of the project in PyPI IMHO.

**Comment by flashcode** [comment]
@yeraydiazdiaz: I already discussed with @graingert, I'm not a simple maintainer of the project, but the owner and the only developer of gitchart. @graingert is not a gitchart developer, he's squatting the project name on PyPI with no valid reason, therefore I'm OK for a transfer of the project to myself.
Thank you for your action.

**Comment by yeraydiazdiaz** [comment]
@graingert since you've been unable to explain why you refuse @flashcode his right to the PyPI project in separate ocassions I'm going to have to declare the project invalid due to copyright infringement and transfer the project to him. I will now ask an admin to perform the transfer.

FWIW situations like this, while covered by PEP 541, are less than ideal. We as volunteers expect the members of our community to be reasonable and help us out in our efforts.

**Comment by graingert** [comment]
Copyright infringement is a very serious allegation, I'm legally
distributing the material under licence

**Comment by yeraydiazdiaz** [comment]
I am obviously not a lawyer so it's perfectly possible that you are in your right to distribute the material. That, however, is not a reason for you refuse the original author of the software ownership of the PyPI project.

You're arguing my reasoning but failing to present a valid one for your own behaviour.

**Comment by graingert** [comment]
> User A owns a project X outside the Package Index. User B creates a
package under the name X on the Index. After some time, User A wants to
publish project X on the Index but realizes name is taken. This is true
even if User A's project X gains notability and the User B's project X is
not notable.

**Comment by flashcode** [comment]
@graingert: you're distributing the same software, not a different project with the same name, so that's different. I'm the only owner of the project, if you want to distribute it respecting the GPL license (with or without changes), then please make a fork with a different name.

**Comment by ewdurbin** [comment]
Given that:

  - The current project on PyPI and associated GitHub repository are going on three years without maintenance or release
  - They are a fork and republication without any changes to the codebase itself
  - The original upstream project is active and prepared to publish to PyPI
  - The two conflicting maintainers do not appear to be willing to compromise/work with one another

This transfer has been completed.

**Comment by flashcode** [comment]
Thank you @ewdurbin.
