### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dgknrsln** [pypa/pypi-support#944]
### PyPI Username

dgknrsln

### Reason for request

Due to unexpecting reset in my phone I "lost 2FA authentication security token".

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
