### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by DigitalWolf98** [pypa/pypi-support#971]
### PyPI Username

`DigitalWolf98`

### Reason for request

I updated my phone, but forgot about transferring 2FA codes, thereby losing access to them. I know my username, password, and email address from the account and can easily provide them as contact information. Please help me restore access.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
